### ISSUE TITLE
"final" is a reserved keyword but also the name of an attribute in QProperty

### ISSUE THREAD

**Issue by BenFordTytherington** [KDAB/cxx-qt#1002]
since final is a reserved word in rust, it cannot be used in struct fields, which is easy enough to avoid, but also currently not supported in the macro e.g. `#[qproperty(T, NAME, read, final)]` will error in the parser, as it does not allow keywords in the declaration. Potential fix by changing macro to use all caps names like `#[qproperty(T, NAME, READ, WRITE = my_setter, FINAL)]`. This also matches Qt but looks a bit odd for Rust code.

**Comment by ahayzen-kdab** [comment]
I wonder if we should copy what Qt is doing, as `final` is also a keyword in C++, and as we have found before copying Qt avoids issues later on. So maybe we use capitals which then for a Qt developer at least feels familiar :-) @LeonMatthesKDAB any thoughts?

**Comment by LeonMatthesKDAB** [comment]
Hm, not a big fan of having to use all-caps, but until we have a better idea, let's go for it.
We can always support lower-case as well if we figure out a way around it.

Good catch @BenFordTytherington

**Comment by ahayzen-kdab** [comment]
I think the way around it is probably `r#final` like #211 but tbh `#[qproperty(T, name, ..., r#final)]` seems much worse than `#[qproperty(T, name, ..., FINAL)]`. And can't remember what happens with syn with these r-values, think they might have been a slightly odd type.

So for me capitals is best for now as well.

**Comment by LeonMatthesKDAB** [comment]
As we have a solution for this in #1003 I think we can close this.
