### ISSUE TITLE
Make CXX-Qt-lib features opt-in

### ISSUE THREAD

**Issue by LeonMatthesKDAB** [KDAB/cxx-qt#1011]
Currently we have CXX-Qt-lib just use all Qt modules by default, with an opt-out for each Qt module.

That is convenient for our examples, but problematic from a systems architecture perspective.

As soon as one library forgets to disable the unnecessary features, everything down the line now automatically links to all Qt modules.

So having it opt-in is safer.
We can also provide a `"full"` feature that we'll use in our examples that just enables everything.

**Comment by ahayzen-kdab** [comment]
Done via #1069
