### ISSUE TITLE
Deprecate the automatic renaming?

### ISSUE THREAD

**Issue by LeonMatthesKDAB** [KDAB/cxx-qt#1070]
We recently had a discussion about the automatic renaming.
It's very hard to teach and inconsistent with CXX, so we think it could be worth removing it.

The most problematic thing about this is the automatic qproperty generation.
We think we've found a solution that ends up in a generation that isn't a disaster.
As my laptop crashed in the middle of the call, I only managed to get a screenshot of the resulting generation:
![PXL_20240911_152709700](https://github.com/user-attachments/assets/7eaaf9d3-f40d-4074-afb0-687c4746a31c)
So we'll explore this in a PR, hopefully before 0.7.

Related to: #828

**Comment by BenFordTytherington** [comment]
Started work in https://github.com/KDAB/cxx-qt/pull/1072,
Not sure if that hits all those names correctly but there's at least some progress.

**Comment by ahayzen-kdab** [comment]
This is now done as #1078 has landed ?
