### ISSUE TITLE
weird symlinking error on windows?

### ISSUE THREAD

**Issue by CelestialCrafter** [KDAB/cxx-qt#1120]
hi! im getting an error while building my project on windows, but it builds fine on linux.

```
C:\Users\Celestial\Documents\fenlu\nodes\sink-frontend>cargo build
   Compiling cxx-qt v0.7.0
error: failed to run custom build command for `cxx-qt v0.7.0`

Caused by:
  process didn't exit successfully: `C:\Users\Celestial\Documents\fenlu\nodes\sink-frontend\target\debug\build\cxx-qt-d42316ea98c17eb5\build-script-build` (exit code: 101)
  --- stdout
  cargo::rerun-if-changed=include/
  cargo::rerun-if-changed=include/connection.h
  cargo::rerun-if-changed=include/signalhandler.h
  cargo::rerun-if-changed=include/thread.h
  cargo::rerun-if-changed=include/threading.h
  cargo::rerun-if-changed=include/type.h
  cargo::rerun-if-changed=src/connection.rs
  cargo::rerun-if-changed=src/connection.cpp

  --- stderr
  thread 'main' panicked at C:\Users\Celestial\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cxx-qt-build-0.7.0\src\lib.rs:1026:25:
  Failed to create symlink `cxx-qt` for export_include_directory: C:\Users\Celestial\Documents\fenlu\nodes\sink-frontend\target\debug\build\cxx-qt-2f7fe7d391714b2a\out\include\cxx-qt
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

the directory exists, and the error isnt that detailed, so i dont really know what to do.
here's my build.rs:

```rust
use cxx_qt_build::{CxxQtBuilder, QmlModule};

fn main() {
    CxxQtBuilder::new()
        .qt_module("Network")
        .qml_module(QmlModule {
            uri: "sinkfrontend",
            rust_files: &["src/qt/media.rs", "src/qt/actions.rs",],
            qml_files: &["qml/main.qml", "qml/Media.qml", "qml/MediaBackground.qml", "qml/MediaDetails.qml", "qml/CustomScrollGridView.qml", "qml/ActionsContextMenu.qml"],
            ..Default::default()
        })
        .build();
}
```

thank you!

**Comment by CelestialCrafter** [comment]
contents of directory:
```
C:\Users\Celestial\Documents\fenlu\nodes\sink-frontend\target\debug\build\cxx-qt-2f7fe7d391714b2a\out\include\cxx-qt>ls
connection.h  signalhandler.h  thread.h  threading.h  type.h
```

**Comment by ahayzen-kdab** [comment]
Symlinks are "fun" on Windows and are a privileged action on Windows, have you tried `enabling Developer Mode, granting the SeCreateSymbolicLinkPrivilege privilege, or running the process as an administrator` as described in the Rust docs.

https://doc.rust-lang.org/stable/std/os/windows/fs/fn.symlink_dir.html#limitations

**Comment by CelestialCrafter** [comment]
worked! thank you

**Comment by jnbooth** [comment]
The symlinks can cause other things to break on Windows as well, such as the compiler not being able to find include files  inside the cxx-qt-lib/ folder. I would also prefer not to need to include a section about enabling Developer Mode in the README of every project I use cxx-qt for.

@ahayzen-kdab, if I were to create a PR for cxx-qt-build to copy header files rather than symlinking their directories, would that be a welcome change? I also noticed a comment in its source code: "TODO: If it's neither unix nor windows, we should probably just deep-copy the dependency headers into our own include directory." It seems like symlinking is more trouble than it's worth.

**Comment by ahayzen-kdab** [comment]
Are symlinks really that broken on Windows? :-( Or is it a separate bug that include files are not working, it might just need to be passing a resolved path or something.

At the moment I'd prefer to at least keep symlinking on Linux/UNIX systems, maybe on Windows we can either deep copy or detect when symlinks aren't going to work and fallback.

We should also note that we are about to refactor the build system code during the 0.8 cycle, so something to consider @LeonMatthesKDAB

**Comment by LeonMatthesKDAB** [comment]
@jnbooth Of course not having to enable developer mode would be good.
So I'm happy to accept a PR that implements the `symlink_directory` function in cxx-qt-build with a deep-copy on windows and other systems.
As long as it keeps the symlinking on unix, as there it's the best solution.
While you're at it, it would also be good to move that function into the `dir` module.
