### ISSUE TITLE
What is the equivalent for QFileInfo

### ISSUE THREAD

**Issue by ikouchiha47** [KDAB/cxx-qt#1126]
Hi, I was trying the quicknanobrowser example from qt. I stumbled across [QFileInfo](https://doc.qt.io/qt-6/qfileinfo.html) . 
Here are the tutorial links:
- [python](https://doc.qt.io/qtforpython-6/examples/example_webenginequick_nanobrowser.html)
- [c++](https://code.qt.io/cgit/qt/qtwebengine.git/tree/examples/webenginequick/quicknanobrowser?h=6.8) 

I am trying to do it in rust. Or will a simple check with fs work as well? Or do we have to write a bridge module?

I didn't see a qfileinfo or something similar in `qt_standalone_types/cpp` , like i had found qstring.h . So its not implemented?

**Comment by ahayzen-kdab** [comment]
So there are three options either

- the type is wrapped and added to cxx-qt-lib(-extras)
- you just use the Rust std::fs APIs https://doc.rust-lang.org/stable/std/fs/index.html
- you use extern "C++" / extern "C++Qt" to declare any API you specifically need

If you are doing all of the file API on the Rust side (as you likely should be with a split between backend and frontend), then just use the Rust `std::fs` APIs there is no need to wrap the Qt QFileInfo API.

If you are needing to store an object from Qt that is a QFileInfo on your backend then you could use extern "C++" / extern "C++Qt" to declare the type as known to CXX and add any API you may need.

But I suspect you are likely trying to check if a file exists or read a file contents or path, which can then be read via `std::fs` ( eg exists https://doc.rust-lang.org/stable/std/fs/fn.exists.html ) and converted into a QUrl/QString/QByteArray if you need to pass any of that info across to Qt / QML.

**Comment by ikouchiha47** [comment]
Does QtWebEngine also no exist? How can I add it?

**Comment by ahayzen-kdab** [comment]
We don't have any existing bindings for QtWebEngine, you can construct them using extern C++ or extern C++Qt blocks https://kdab.github.io/cxx-qt/book/bridge/extern_cppqt.html or even maybe autocxx.

But you also have to consider what are you trying to do in Rust that requires QtWebEngine ? It is more likely that it should be used in QML or in C++ for Qt Widgets and then Rust should be exposing models and properties of eg QUrls to the frontend. Rather than trying to use Qt WebEngine from Rust directly. But I also don't know your use case.

**Comment by ikouchiha47** [comment]
Yeah you are right. So basically I was trying one of the quicknanobrowser examples from QT . I had looked at different offerings, including tauri.
It was between using CEF directly or using Qt . Qt had better docs, and I was finding it hard to accept I need to do C++ to build ui. So cxx-qt was the main reason for using Qt . 

This is the original repo: [https://code.qt.io/cgit/qt/qtwebengine.git/tree/examples/webenginequick/quicknanobrowser?h=6.8.0](https://code.qt.io/cgit/qt/qtwebengine.git/tree/examples/webenginequick/quicknanobrowser?h=6.8.0) . I was trying to see, if I could port it in rust. I am using the QML. Most things are same except for utils.h and main.cpp . I followed the example from `qt without cmake` , And this is where I got stuck. 


Some example.

// main.rs

```rust
pub mod cxxqt_object;

use cxx_qt_lib::{QGuiApplication, QQmlApplicationEngine, QUrl};

fn main() {
    // Create the application and engine
    let mut app = QGuiApplication::new();
    let mut engine = QQmlApplicationEngine::new();

    // Load the QML path into the engine
    if let Some(engine) = engine.as_mut() {
        engine.load(&QUrl::from(
            "qrc:/qt/qml/com/hyperion/cxx_qt/base/qml/main.qml",
        ));
    }

    if let Some(engine) = engine.as_mut() {
        // Listen to a signal from the QML Engine
        engine
            .as_qqmlengine()
            .on_quit(|_| {
                println!("QML Quit!");
            })
            .release();
    }

    // Start the app
    if let Some(app) = app.as_mut() {
        app.exec();
    }
}
```

// main.qml

```qml
import QtQuick 
import QtWebEngine

// This must match the uri and version
// specified in the qml_module in the build.rs script.
import com.hyperion.cxx_qt.base 1.0

QtObject {
    id: root

    property QtObject defaultProfile: WebEngineProfile {
        offTheRecord: false
        storageName: "Profile"
        
        Component.onCompleted: {
            // let fullVersionList = defaultProfile.clientHints.fullVersionList;
            // fullVersionList["Hyperion"] = "1.0";
            // defaultProfile.clientHints.fullVersionList = fullVersionList;
            // console.log(defaultProfile.clientHints)
        }

    }

    property QtObject otrProfile: WebEngineProfile {
        offTheRecord: true
    }

    property Component browserWindowComponent: BrowserWindow {
        applicationRoot: root
    }
    property Component browserDialogComponent: BrowserDialog {
        onClosing: destroy()
    }
    function createWindow(profile) {
        console.log("create window")
        var newWindow = browserWindowComponent.createObject(root);
        newWindow.currentWebView.profile = profile;
        profile.downloadRequested.connect(newWindow.onDownloadRequested);
        console.log("new", newWindow);
        return newWindow;
    }
    function createDialog(profile) {
        var newDialog = browserDialogComponent.createObject(root);
        newDialog.currentWebView.profile = profile;
        return newDialog;
    }
    function load(url) {
        var browserWindow = createWindow(defaultProfile);
        browserWindow.currentWebView.url = url;
    }
}
```

I was getting the error:

```shell
Running target/debug/hyperbase
QtWebEngineQuick::initialize() must be called from the Qt gui thread.
```

so when I tried to import QtWebEngineQuick , I couldn't find it. Hence the question.

**Comment by ahayzen-kdab** [comment]
Ah I see :-)

So you basically need to call `QtWebEngineQuick::initialize()` from your main. This initially looks like a static method which CXX doesn't support yet which would mean you'd need to create a function in C++ to proxy to it, but it actually turns out that this is just a function in a namespace so i think the following might work.

Here is the C++ code where you can see that this is a namespace and not a class.

```cpp
namespace QtWebEngineQuick
{
    Q_WEBENGINEQUICK_EXPORT void initialize();
}
```
https://github.com/qt/qtwebengine/blob/a05139fa2266cc281e0b2b362dd5a52572de1dd7/src/webenginequick/api/qtwebenginequickglobal.h#L22-L25

So put this somewhere in a cxx / cxx-qt bridge macro

```rust
#[cxx::bridge]  // one of your bridges
mod ffi {
  ...

  unsafe extern "C++" {
    include!(QtWebEngineQuick/qtwebenginequickglobal.h");

    #[namespace = "QtWebEngineQuick"] // here we match the namespace
    #[rust_name = "qtwebenginequick_initialize"]  // here we can pick a nicer name for Rust than initialize
    fn initialize();  // here we match the C++ function
  }
}
```

Then you can call this in the main function.
```rust
ffi::qtwebenginequick_initialize();
```

Then also ensure that you have `webenginequick` as a Qt module in the build script and it should work :crossed_fingers:

**Comment by ikouchiha47** [comment]
Awesome, thanks a lot.

**Comment by ahayzen-kdab** [comment]
Feel free to close the issue if it does work (as i haven't tested it myself). And note that we do have a Zulip channel if you prefer chat over issues in the future etc https://cxx-qt.zulipchat.com :-)

**Comment by ikouchiha47** [comment]
Ok. Will join the channel. Thanks :)
