### ISSUE TITLE
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa"

### ISSUE THREAD

**Issue by AllenDang** [KDAB/cxx-qt#1134]
I built a static version of qt6.8.0 with following config
```
cd qt6_build
../configure -init-submodules -prefix ~/SDK/qt6/ -static
cmake --build . --parallel
cmake --install .
``` 

And when I try to run `cargo run -p qml-minimal-no-cmake`, following error occurred.

```
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in "/Users/allen/SDK/qt6/plugins/"
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

fish: Job 1, 'cargo run --release' terminated by signal SIGABRT (Abort)
```

**Comment by ahayzen-kdab** [comment]
Thanks for taking the time to report this issue.

This normally means that your Qt install is not configured / setup fully.

For example, Qt might not have been able to configure cocoa properly when building, or parts of Qt are missing from your PATH or that the lib/ folder is in your LD path (i note you are on MacOS so you might have frameworks to deal with).

Can you try running the program with `QT_DEBUG_PLUGINS=1` set to see if this gives any more clues? And also can you try running a minimal QML app eg run `qmlscene path/to/window.qml` to see if that works ?

**Comment by AllenDang** [comment]
@ahayzen-kdab I think I know what's going on right now, turns out I have a qt6 installed via home-brew, and a static build version of qt6 in another directory, after uninstall the home-brew version, it works fine now, :P
