### ISSUE TITLE
Consider supporting arbitary structs and impl blocks in the module

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#118]
Currently we only support the structs Data and RustObj, consider allowing unknown structs.

Related to #32 and #80

**Comment by LeonMatthesKDAB** [comment]
Make sure typos don't end up creating weird compiler issues (i.e. someone typed `data` instead of `Data`).

**Comment by ahayzen-kdab** [comment]
With the new API this is now irrelevant as we are a CXX module.
