### ISSUE TITLE
Once Ubuntu 22.04 is available in CI update packages

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#121]
- [ ] Remove PPA usage and use Qt 5 and 6 from the distro
- [ ] Move to clang-format-14 and try to pin the brew package on macOS to the same version

**Comment by Be-ing** [comment]
>  try to pin the brew package on macOS to the same version

I don't think Homebrew supports pinning. This is one reason I prefer vcpkg over Homebrew, though vcpkg doesn't package clang-format.

**Comment by ahayzen-kdab** [comment]
Note that you can install `clang-format@11` (eg https://formulae.brew.sh/formula/clang-format@11 ) or `clang-format@8` this would be a good enough "pin" (same as Linux) but we need at least clang-format-12. So once we move to Ubuntu 22.04 we should be able to move to `clang-format-14` and "pin" to `clang-format@14` in brew (however it appears it's not obvious which versions remain for long periods of time in brew)

**Comment by Be-ing** [comment]
After 20.04 was released:

https://github.blog/changelog/2020-10-29-github-actions-ubuntu-latest-workflows-will-use-ubuntu-20-04/

> GitHub Actions has supported Ubuntu-20.04 in preview mode since June 2.

So it may be a month or two before 22.04 is available on GitHub Actions.
