### ISSUE TITLE
Figure out what changes are required for building on Linux arm64 / armhf

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#128]
# Native

- [ ] Test if we can build on arm64
- [ ] Test if we can build on armhf

# Cross compiling

- [ ] Support a custom `--target` for cargo eg `aarch64-unknown-linux-gnu`
- [ ] Potentially set a `--target-dir` to have a common target folder? or can we use the target above and known when it's non-native

# CI

- [ ] Can we use `qemu-user-static` with eg `gcc-aarch64-linux-gnu` and `libc6-dev-arm64-cross` ?
- [ ] Pass the target eg `aarch64-unknown-linux-gnu` to the rust action

**Comment by Be-ing** [comment]
>  Can we use qemu-user-static with eg gcc-aarch64-linux-gnu and libc6-dev-arm64-cross ?

Emulating ARM builds would be very slow, but cross compiling would be more practical to run regularly on CI.

**Comment by ahayzen-kdab** [comment]
So i found out you can use docker/podman in github action machines, i need to see how many permissions there are available as then there is a potentially simple way of building for ARM.

Otherwise we'd have to sort out the CMake to work with cross compiling, potentially after CMake refactors.

But in good news we are able to build natively on ARM and have things works :-)

**Comment by Be-ing** [comment]
Yes, you can do that, but IIUC Docker or Podman will internally use QEMU emulation which will probably take hours per build.

**Comment by ahayzen-kdab** [comment]
We now have CI builds for ARM64 on macOS via M1 and we build for wasm32 for WebAssembly so should cover any ARM64 quirks and any 32 bit fun for armhf (which is less common anyway now), therefore closing.
