### ISSUE TITLE
Error Compiling the getting started application in Book

### ISSUE THREAD

**Issue by Ayush1325** [KDAB/cxx-qt#129]
I was trying to build the getting started example as given in the [Book](https://kdab.github.io/cxx-qt/book/getting-started/5-cmake-integration.html). However, I get the following error when I try to build it:
```
CMake Error at CMakeLists.txt:44 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "cxx_qt_getting_started".  All uses of target_link_libraries
  with a target must be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * /var/home/ayush/Documents/Programming/Qt/cxx-qt/cmake/CxxQt.cmake:109 (target_link_libraries)
```

This seems to be solved if we specify PUBLIC/PRIVATE in for the Qt dependencies as mentioned [here](https://stackoverflow.com/questions/59522267/cmake-rejects-a-second-target-link-libraries-talking-about-keyword-vs-plain).

So the CMakeLists.txt should look something like this:
```cmake
cmake_minimum_required(VERSION 3.16)

project(cxx_qt_getting_started)
set(APP_NAME ${PROJECT_NAME})

set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(QT NAMES Qt6 Qt5 COMPONENTS Core Gui Qml QuickControls2 QuickTest Test REQUIRED)
find_package(Qt${QT_VERSION_MAJOR} COMPONENTS Core Gui Qml QuickControls2 QuickTest Test REQUIRED)

# Include the CXX-Qt CMake code, which provides some easy functions
# to generate the CXX-Qt code.
include(CxxQt)

# Generate C++ code from Rust using Cargo in the current folder
cxx_qt_generate_cpp(GEN_SOURCES)

# Define our sources
set(
    CPP_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/src/main.cpp
)

set(
    RESOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/src/qml.qrc
)

# Define our executable with our C++ source, generated sources, and QML resource files
add_executable(${APP_NAME} "${CPP_SOURCES}" "${GEN_SOURCES}" "${RESOURCES}")

# Include generated sources
cxx_qt_include(${APP_NAME})

# Link to generated rust library
cxx_qt_link_rustlib(${APP_NAME})

# Link to Qt in the normal way
target_link_libraries(${APP_NAME} PUBLIC/PRIVATE
    Qt${QT_VERSION_MAJOR}::Core
    Qt${QT_VERSION_MAJOR}::Gui
    Qt${QT_VERSION_MAJOR}::Qml
    Qt${QT_VERSION_MAJOR}::QuickControls2
)
```

**Comment by ahayzen-kdab** [comment]
Thanks for taking the time to report this issue :-)

Looks like a mistake was made when changing CxxQt.cmake thanks for pointing out the cause, i've submitted a change to use `PRIVATE` in the Rust book.

But I think it would also be good for this example to come from real code (like the qml_minimal example). @LeonMatthesKDAB  maybe we could have the cxx-qt-getting-started example embedded into the repository so that the book can include real code and we can then have tests checking it builds? :-)

**Comment by LeonMatthesKDAB** [comment]
Hm, IIRC, the example in the book is basically the exact same as the qml-minimal example, apart from a bit of different naming in the CMakeLists.txt.
I didn't feel like duplicating the entire code base just to be able to link the CMakeLists.txt file.
But maybe that was a mistake.

Probably best to just to include the `CMakeLists.txt` file from the `qml-minimal` example and just use that naming.
