### ISSUE TITLE
How to build with qmake?

### ISSUE THREAD

**Issue by jason-yau** [KDAB/cxx-qt#138]
In general, I use qmake to build QT applications. How do I build apps with it?

**Comment by ahayzen-kdab** [comment]
Currently we only support CMake, I believe Qt is also moving in this direction so hence we have added that support first.

What would be required of qmake is the steps described in the CMake integration https://kdab.github.io/cxx-qt/book/concepts/cmake.html

- Use cargo to generate the C++ sources from the Rust code
- Add those generated C++ sources to the qmake list
- Include any generated folders of CXX-Qt / CXX sources
- Link the resultant Rust library to the C++ library/binary

Do note that we plan to change how the CMake works, one change might be to have a builder tool that does the first step listed above ( this is described in #106 ) which could help qmake integration later on.

**Comment by Be-ing** [comment]
Now that cxx-qt-build compiles the C++ code it generates, there would be less required to use cxx-qt with other C++ build systems. All the C++ build system needs to do now is:

1. Set CXXQT_EXPORT_DIR environment variable to tell cxx-qt-build where to output the C++ headers it generates
2. Add CXXQT_EXPORT_DIR/crate-name to the C++ include paths
3. Set QMAKE environment variable to the name (or better yet, absolute path) of the qmake executable to ensure the C++ build system and cxx-qt-build use the same installation of Qt
4. Call `cargo build`
5. Link the Rust staticlib into the C++ application

**Comment by LeonMatthesKDAB** [comment]
As CMake is the currently preferred build system, even by Qt itself, we do not have plans to support qmake anymore.
