### ISSUE TITLE
Failed to build when using workspace or changing rust outdir

### ISSUE THREAD

**Issue by jason-yau** [KDAB/cxx-qt#139]
The rust library will fail to build using workspace with the following error:
```
--- stderr
thread 'main' panicked at 'Could not create cpp_namespace_prefix file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', .../cxx-qt-build-0.2.1/src/lib.rs:300:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I found that you used the following function to calculate the output of CPP generation directory
```Rust
fn manifest_dir() -> String {
    let mut manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("Could not get manifest dir");
    // CARGO_MANIFEST_DIR uses \ path separators on Windows, but the format! macros that
    // use the return value of this function use / separators. CMake's `file(STRINGS)` command
    // which is used to load list of generated file paths fails if \ and / path separators
    // are mixed. CMake also fails when using all \ separators because it treats them as escaping
    // the character after the \
    if cfg!(windows) {
        manifest_dir = manifest_dir.replace('\\', "/");
    }
    manifest_dir
}
```

It will fail if  developers change the rust library build directory. I think the best way to calculate the output directory is to use `env::var("OUT_DIR")`, such as: 
```Rust
fn get_output_dir() -> String {
    let mut out_dir = std::env::var("OUT_DIR").expect("Could not get out dir");
    out_dir += "/../../../..";
    if cfg!(windows) {
        out_dir = out_dir.replace("\\", "/");
    }
    out_dir
}
```

**Comment by ahayzen-kdab** [comment]
Right this currently doesn't work, it's another thing related to why we need a CMake rewrite. As yes moving things into the OUT_DIR would work for the Rust side of things, but then CMake needs to be to know what folder the OUT_DIR to be able to find the resultant sources etc.

Having a CLI build tool for generating the C++ sources as described in #106 could help here as it could use something similar to cxxbridge like `cxxbridge src/main.rs > path/to/mybridge.cc` etc ( or there could be an option to provide the root folder, or it could just output the `OUT_DIR/path/to/bridge/file` etc ). This would then mean that CMake would run the tool and be able to know where the generated C++ code ends up.

**Comment by jason-yau** [comment]
> Right this currently doesn't work, it's another thing related to why we need a CMake rewrite. As yes moving things into the OUT_DIR would work for the Rust side of things, but then CMake needs to be to know what folder the OUT_DIR to be able to find the resultant sources etc.
> 
> Having a CLI build tool for generating the C++ sources as described in #106 could help here as it could use something similar to cxxbridge like `cxxbridge src/main.rs > path/to/mybridge.cc` etc ( or there could be an option to provide the root folder, or it could just output the `OUT_DIR/path/to/bridge/file` etc ). This would then mean that CMake would run the tool and be able to know where the generated C++ code ends up.

There is a project which is good at Rust and C/C++ Integration and it may solve this issue.
See [https://github.com/corrosion-rs/corrosion](url)
And the following link is a good example that shows us how to use CXX and corrosion with CMake.
[https://github.com/trondhe/rusty_cmake](url)

**Comment by ahayzen-kdab** [comment]
I think the main fun we'll have is ideally we want to run the C++ generation step at the CMake configure stage, then assuming those sources are added to the CMake target, the remaining build phase with Rust is probably "normal" from the corrosion point of view. Maybe we'll need something custom to do that first step. The rusty_cmake one partially seems to do this, but we must note how we also have a library of extra C++ files that need to be included too, so something to investigate :-)

**Comment by LeonMatthesKDAB** [comment]
I am pretty sure this is no longer an issue.
Let's close it for now, can be reopened if it reappears.
