### ISSUE TITLE
example qml_minimal cannot build

### ISSUE THREAD

**Issue by iujakchu** [KDAB/cxx-qt#142]
qml_minimal demo cannot build which throws:
```
CMake Error at CMakeLists.txt:92 (add_valgrind_test):
  Unknown CMake command "add_valgrind_test".
Call Stack (most recent call first):
  CMakeLists.txt:99 (add_qml_test)
```
adding 
```
function(add_valgrind_test NAME_WITH_PREFIX BINARY WORKING_DIRECTORY)
    add_test(NAME ${NAME_WITH_PREFIX}_valgrind
        COMMAND ${MEMORYCHECK_COMMAND} ${MEMORYCHECK_COMMAND_OPTIONS} --suppressions=${MEMORYCHECK_SUPPRESSIONS_FILE} --gen-suppressions=all ${BINARY}
        WORKING_DIRECTORY "${WORKING_DIRECTORY}"
    )
endfunction()
```
in [CMAKELISTS.txt](https://github.com/KDAB/cxx-qt/blob/main/examples/qml_minimal/CMakeLists.txt) solves this.
But I'm not familiar with cmake ,not quite sure if this is the right way to handle this problem.

**Comment by ahayzen-kdab** [comment]
This sounds like you are trying to run CMake for only the `examples/qml_minimal` directory ? Most of our CMake assumes that you are building from the root directory and then running a chosen target (eg there is a target called `examples_qml_minimal`).

However if are just trying to try out the `qml_minimal` example by itself you could comment out all the unit test related code (eg the `add_qml_test` function and everything in it).

**Comment by LeonMatthes** [comment]
We can also add CMake options that disable the test code by default.

Generally, it might be a good idea to check that we can actually build the exampkes by themselves...

**Comment by ahayzen-kdab** [comment]
Yup having a flag whether to run tests or not would be quite simple and probably allow all the examples to be built standalone.

**Comment by iujakchu** [comment]
Thanks for your response,I built it successfully.
