### ISSUE TITLE
Use full module path in generated rust code to avoid collisions

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#19]
Use full module path in generated source paths, so src/moda/lib.rs with the contents mod modb { mod modc { our macro around mod my_object } } would become src/moda/modb/modc/my_object.h. This helps later if we allow for generating objects into different QML namespaces.

At the moment it's possible to cause two modules to collide in generation.

There will be fun here around sub objects, might even simplfy code as sub objects use fully qualified names?

**Comment by ahayzen-kdab** [comment]
Note that the path of mod's can be influenced by an attribute https://doc.rust-lang.org/reference/items/modules.html#the-path-attribute

We will need to track the full mod path somehow.

**Comment by ahayzen-kdab** [comment]
Also note that this will need to affect the C++ namespace and file generation too, and the include paths will need updating.

**Comment by ahayzen-kdab** [comment]
To avoid collisions in QML we may need to allow for a custom name to be specified in the macro, eg `#[cxx_qt(QObject, qml_name = "MyObject")]`

**Comment by LeonMatthesKDAB** [comment]
> To avoid collisions in QML we may need to allow for a custom name to be specified in the macro, eg `#[cxx_qt(QObject, qml_name = "MyObject")]`

I don't think this is necessary, as qmlRegisterType can rename the C++ type.

**Comment by ahayzen-kdab** [comment]
The original bug is irrelevant now as you can choose the `cxx_file_stem`, maybe we should see if that could contain slashes for folders. Then note we might start using `QML_ELEMENT` for registering instead of qmlRegisterType #241 , but this is a separate issue, so lets close this old issue.
