### ISSUE TITLE
Rename C++ members and methods to avoid collisions

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#20]
Rename C++ members so that more Q_PROPERTY names are available eg use m_internalRustObj, m_propertyObj, m_mutexInternalRustObj, m_mutexPropertyObj etc

So there could be the following prefixes
- internal
- property
- mutex

Also consider if there are any names we cannot avoid collisions and we should error if they are used in Rust (and if this should move to another issue).

**Comment by ahayzen-kdab** [comment]
We also need to consider how to avoid collisions on the Rust side eg for wrappers, a separate struct is possible but tricky as C++ would need to call through that to the actual object.

Instead consider using a prefix of `cxx_qt_` on our helper methods, with the possibility to override the prefix name in the `build.rs` like the C++ namespace.

cc @LeonMatthesKDAB

**Comment by ahayzen-kdab** [comment]
Also note that the task of ensuring all the C++ methods are namespaced is linked to avoiding collisions #14

**Comment by LeonMatthesKDAB** [comment]
> We also need to consider how to avoid collisions on the Rust side eg for wrappers, a separate struct is possible but tricky as C++ would need to call through that to the actual object.
> 
> Instead consider using a prefix of `cxx_qt_` on our helper methods, with the possibility to override the prefix name in the `build.rs` like the C++ namespace.
> 
> cc @LeonMatthesKDAB

+1 for using a prefix like `cxx_qt_` on our generated code.
That would also make it easier to see in a stack-trace, where cxx-qt ends and user code starts.

**Comment by ahayzen-kdab** [comment]
This is becoming increasingly less relevant, as methods now map to the rust ones. We might have a checks phase which could ensure that properties and invokables or reserved names don't collide - but we are also trying to lean on the compiler. For now lets leave this open and review in the next cycles if anything is needed.

**Comment by ahayzen-kdab** [comment]
Moving our `invokableWrapper` in C++ to private + named better could also help.

**Comment by LeonMatthesKDAB** [comment]
That doesn't seem to be a problem anymore, as we have barely anything inside the C++ side of things.
