### ISSUE TITLE
Add support for r#type field?

### ISSUE THREAD

**Issue by jason-yau** [KDAB/cxx-qt#211]
As title.

**Comment by ahayzen-kdab** [comment]
@jason-yau are you able to explain a bit more about the use case of `r#type` field ? Do you mean in 0.3 in the Data struct to define a property name ? Eg you want to be able to do
```
struct Data {
  r#type: f32,
}
```
?

**Comment by jason-yau** [comment]
This is only my personal opinion. I think there is no reason to prohibit developers from defining `type` in structs/classes exposed to C++, since`type` is not a keyword in C++.

**Comment by ahayzen-kdab** [comment]
Makes sense, we'll see to see what this looks like when it goes through `syn`. Something to look at after the refactor of the code though :-)

**Comment by jason-yau** [comment]
> Makes sense, we'll need to see what this looks like when it goes through `syn`. Something to look at after the refactor of the code though :-)

Alternatively, rename fields by attribute，like `#[cxx_name = “type”]` in `cxx` crate

**Comment by LeonMatthesKDAB** [comment]
You can rename fields with cxx_name and rust_name, and we no longer have implementations in the bridge, so this is probably no longer needed.
