### ISSUE TITLE
Create a Rust book

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#23]
- [ ] Write existing sections, eg QObject, Data, RustObj, invokable, properties, handle property change, threading update etc
- [ ] Write future sections, eg QAbstractListModel, Roles, enum etc
- [ ] When on Github integration with CI for Github pages? https://rust-lang.github.io/mdBook/continuous-integration.html#deploying-your-book-to-github-pages
- [ ] Ensure we clearly describe which types are trivial and not in a table or something so that users know when to use Variant vs QVariant etc
- [ ] Safety lines in qcolor etc have TODOs which could be linked to an advanced section in the book about internals

https://rust-lang.github.io/mdBook/

**Comment by Be-ing** [comment]
Can this be closed now?

**Comment by ahayzen-kdab** [comment]
Yes lets close this and open new issues for any more tasks relating to the book :-)
