### ISSUE TITLE
ahead-of-time compilation of QML

### ISSUE THREAD

**Issue by Be-ing** [KDAB/cxx-qt#242]
It would be nice if qt-build could call qmlcachegen (Qt5) or qmlsc (Qt6).

https://www.qt.io/blog/the-new-qtquick-compiler-technology

However qmlsc is not open source yet:

> qmlsc is available for commercial customers and some of its features are merged into qmlcachegen, which continues to be available with all versions of Qt.

https://doc.qt.io/qt-6/qtqml-tool-qmlsc.html

**Comment by ahayzen-kdab** [comment]
There is also the `qmltc` https://doc.qt.io/qt-6/qtqml-tool-qmltc.html https://www.qt.io/blog/qml-type-compilation

And we should support commercial tools as well.

**Comment by Be-ing** [comment]
> qmlcachegen is helpful in any case when qmltc isn't used.

I asked about this on a [recent Qt blog post](https://www.qt.io/blog/compiling-qml-to-c-a-4x-speedup) and this isn't quite right. qmlcachegen is always helpful. qmltc can be used together with qmlcachegen; they work on different aspects of speeding up QML.

**Comment by Be-ing** [comment]
> Qt 6.5 will add a new [QQmlApplicationEngine::loadFromModule function](https://doc-snapshots.qt.io/qt6-6.5/qqmlapplicationengine.html#loadFromModule) which will be able to load qmltc compiled QML types via their QML module URI and type name as QStrings, so we won't need to generate Rust bindings to the generated C++ classes.

This is detailed in a new blog post now that Qt 6.5 has been released: https://www.qt.io/blog/whats-new-for-qml-modules-in-6.5
