### ISSUE TITLE
Have the ability to mark an object as singleton

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#25]
Add option to mark an option as a singleton in the macro attribute, so make_object(singleton = true) or something.

Once #22 is done this might be `cxx_qt(QObject, singleton = true)` or `cxx_qt(QObject(singleton = true))`. Consider if we can hint the QML versions and name here as well.

**Comment by ahayzen-kdab** [comment]
This is only still relevant if we register types at compile time #241 rather than manually in C++.

**Comment by ahayzen-kdab** [comment]
Use `QML_SINGLETON` https://doc.qt.io/qt-6/qqmlengine.html#QML_SINGLETON like #241 this would then be

```
#[cxx_qt::qobject(qml_element, qml_singleton)]
pub struct MyObject {
```

**Comment by ahayzen-kdab** [comment]
Needs Qt 5 CMake command figuring out from #241

**Comment by LeonMatthesKDAB** [comment]
> Use `QML_SINGLETON` https://doc.qt.io/qt-6/qqmlengine.html#QML_SINGLETON like #241 this would then be
> 
> ```
> #[cxx_qt::qobject(qml_element, qml_singleton)]
> pub struct MyObject {
> ```

Insted of using `#[cxx_qt::qobject(qml_element, qml_singleton)]` I'd suggest just using `#[cxx_qt::qobject(qml_singleton)]`.
`qml_singletion` infers `qml_object`.

**Comment by ahayzen-kdab** [comment]
Right, potentially, note that it could also be `qml_named_element(Thing)`. Depends how closely we want to follow Qt here.

**Comment by LeonMatthesKDAB** [comment]
I'd say if our experience tells us that there's a certain "right" way to do something in Qt, let that be the default, instead of following C++/Qt defaults.
Like we do by auto-generating property setters/getters with signal emission.
So if the right way is to use the struct name by default, just use that. Makes the whole thing easier and less boilerplate-y.

**Comment by ahayzen-kdab** [comment]
Right, so probably `#[cxx_qt::qobject(qml_singleton)]`, the biggest problem though is making sure it works in Qt 5.15 CMake

**Comment by LeonMatthesKDAB** [comment]
Depending on whether we even want to support this use case in Qt5?
We could make it a Qt6 only feature...
