### ISSUE TITLE
Make cxx-qt-lib truely optional or depend on it with cxx-qt or does it work currently?

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#319]
Currently cxx-qt-gen assumes that headers such as `convert.h` and `cxxqt_thread.h` will exist, these currently come via cxx-qt-build.

- [x] Ensure that we can build without cxx-qt-lib
  - [x] cxx-qt-gen depends on `cxx_qt_lib::ConnectionType` and `cxx_qt_lib::QMetaObjectConnection` for signals :thinking: 
- [ ] Decide if these header only includes that we always assume exist are in the correct place
- [ ] Check if we need any further linking assumptions (just QtCore?)
- [ ] Can this then be used to register the std numeric types for Qt 5 ? #317 
- [x] Ensure that cxx-qt-build can take a key-value collection of headers and put them in a folder that is in the include target

**Comment by Be-ing** [comment]
What would be the benefit of this, even if it is possible?

**Comment by ahayzen-kdab** [comment]
You could then use our generation with other Qt / CXX libraries and also then use cxx-qt-lib with other C++ binding tools. At the moment cxx-qt-gen assumes that the convert and cxxqtthread headers are coming from somewhere. And if you are using cxx-qt-lib by itself you don't need the convert and cxxqtthread.

So we should ensure that the positioning of these headers is correct, any dependencies are correct, and that each can be built on it's own. Lots of it looks correct already, but having a full and clear separation between layers could prove useful later.

**Comment by ahayzen-kdab** [comment]
Related to #355 but lets investigate in a future cycle.

**Comment by ahayzen-kdab** [comment]
If we ever did this we would likely want to consider moving `cxx_qt_lib_headers::write_headers(format!("{header_root}/cxx-qt-lib"));` out of `cxx-qt-build` and have this as something in the build script or something.

```rust
CxxQtBuilder::new()
   .with_headers("cxx-qt-lib", cxx_qt_lib::headers()
```

Eg something like the above to pass a key-value collection of headers with a folder prefix that should be written somewhere that can then be included.

This has the advantage that developers can write their own independent crates in the same way and they can still be used without cxx-qt-build and cxx-qt-lib being tightly coupled.

Something we should consider if / how we wanted to do this before 1.0 so tagging to remember.

**Comment by ahayzen-kdab** [comment]
cxx-qt-lib is now optional, there could be some further experiments to move things like `std_types_qt5` into `cxx-qt` instead of `cxx-qt-build`, but can be investigated separately.
