### ISSUE TITLE
Have a helper to register all types to the QML engine

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#33]
Currently if you use the QQmlExtensionPlugin all generated types are registered to the QML engine.

But if you don't use the plugin then you currently have to register them manually.

Provide a method somewhere that does this automatically, eg `CxxQtTypes::registerTypes(uri)`.

**Comment by Be-ing** [comment]
I think we should take advantage of Qt 5.15's ability to register QML types at compile time instead: #241

**Comment by ahayzen-kdab** [comment]
Yup this is an old issue that can be closed as it comes from the old API.
