### ISSUE TITLE
test minimum supported Rust version on CI

### ISSUE THREAD

**Issue by Be-ing** [KDAB/cxx-qt#334]

**Comment by ahayzen-kdab** [comment]
Weirdly disappointing that the Rust ecosystem needs this when there are already editions and without tooling to figure out what version would be the lowest :-/ 

Note that CXX has a matrix to test a minimum and the stable versions of Rust https://github.com/dtolnay/cxx/blob/c7060d40361c4d955fc64adf35f67b28b5c75299/.github/workflows/ci.yml#L22 They raised this to 1.60 but didn't bump the rust-version in the cargo fields https://github.com/dtolnay/cxx/blob/c7060d40361c4d955fc64adf35f67b28b5c75299/Cargo.toml#L15
