### ISSUE TITLE
Consider renaming qt_thread to qt_event_loop

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#338]
We currently have the API
```rust
let qt_thread = self.qt_thread();

// in a background thread
qt_thread.queue(move || { ... });
```

However it isn't totally clear what `qt_thread` is and how does `queue` relate, when it's actually just using the Qt event loop internally.

Consider renaming to `qt_event_loop` which describes what is happening internally and that then makes `queue` more obvious.

```rust
let qt_event_loop = self.qt_event_loop();

// in a background thread
qt_event_loop.queue(move || { ... });
```

Then also rename `CxxQtThread` to `CxxQtEventLoop` or `CxxQtEventLoopHandle` etc ?

- [ ] Rename `qt_thread` method
- [ ] Rename `CxxQtThread<T>` type (and the generated `TCxxQtThread`

**Comment by LeonMatthesKDAB** [comment]
I actually think the naming here is alright, as `CXXQtThread` refers to the `QObject::thread`, which is documented as:

> Returns the thread in which the object lives.
 https://doc.qt.io/qt-6/qobject.html#thread

And `queue` queues an event onto the event loop of that specific thread.
So the object that you hold a reference to (`CXXQtThread`) actually refers to a thread, and we could add thread-specific behavior later on (i.e. thread id, etc.).

However, the thread also has an EventQueue, which `queue` makes convenient to access.
We could consider renaming `queue` to `event_loop`, which returns an EventLoop type that then has the `queue` method on it.
But I think that's rather convoluted.

**Comment by ahayzen-kdab** [comment]
Which would then make this issue closed :-) Reading the thread id yes could be useful to later. Just as long as the `qt_thread().queue(...)` is natural.

And if the CXXQtThread did have more info on it, would it then prevent it from being `Send` ? But it's sent via a UniquePtr<CXXQtThread> which is `Send` so maybe this wouldn't be an issue?

**Comment by LeonMatthesKDAB** [comment]
For that we wouldn't actually need to change the implementation of CxxQtThread.
It already contains a pointer to the QObject, which we could ask for the QThread on demand.
It's more about adding more access functions, than changing any of the existing behavior.

So I don't see anything that would prevent it from staying `Send`.

Closing the issue would be fine by me :)

**Comment by ahayzen-kdab** [comment]
Keeping this as `qt_thread` for now.
