### ISSUE TITLE
Consider allowing to make the Signals enum private

### ISSUE THREAD

**Issue by LeonMatthesKDAB** [KDAB/cxx-qt#375]
Currently if the `#[cxxqt::signals()]` enum is not `pub`, the compiler errors that a private type is leaked in public API (likely due to the `emit` function).

A potential fix might be to:
1. Make `emit` private by default (it's probably bad to emit signals on an object you don't own anyway)
2. Have `emit` mirror the visibility of the signals enum (i.e. if the signals enum is pub, emit is pub as well).
3. Keep the status quo (does it even make sense to have "private signals"?)

**Comment by ahayzen-kdab** [comment]
Note that in C++ signals are normally public functions so can be emitted on an object you don't own.

**Comment by ahayzen-kdab** [comment]
With the new API this seems irrelevant ? There is no signals enum and no emit method, everything is normal CXX bridges with their normal rules. Therefore closing ...
