### ISSUE TITLE
Figure out API for supporting list models

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#40]
We need support for the following items

- Row struct , which will declare roles (unless we use generic enums from #34 )
- Have a Model or ItemModel trait which implements the model methods
- Have support in the macro for defining different base object (eg `cxx_qt(QAbstractItemModel)`)
- Signal support for emitting signals #31 
- A way to trigger beginInsertRows / remove / reset ?
- When a signal arrives and we handle it, we need a way to perform model tasks. Eg handle_signal needs to then trigger set_data or insert_row, but this needs to go back to the C++ side and not just be on the rust side like an invokable?

```
// what happens for qabstractitemmodel, qabstracttablemodel, qstandardmodel etc ?
#[make_qabstractlistmodel]
mod my_model {
    #[derive(Default)]
    pub struct Row {
        first_name: String,
        last_name: String,
    }
 
    #[derive(Default)]
    struct RustObj {
        items: Vec<Row>,
    }
 
    // TODO: need a way to trigger dataChanged() from another thread
 
    // TODO: need a way to trigger beginInsertRows / remove / reset / move etc
 
    impl unsafe Model<CppObj, Role> for RustObj {
        // TODO: what do we return here ? some kind of variant or an enum?
        fn data(&self, index: i32, role: Role) -> Option<Value> {
            if let Some(row) = self.items.get(index) {
                let value = match role {
                    Role::FirstName => row.first_name.into(),
                    Role::LastName => row.last_name.into(),
                }
                Some(value)
            } else {
                None
            }
        }
 
        // TODO: QAbstractItemModel takes a parent: QModelIndex
        fn row_count(&self) -> i32 {
            self.items.len()
        }
 
        fn set_data(&mut self, index: i32, value: Value, role: Role) -> bool {
            if let Some(row) = self.items.get_mut(index) {
                match role {
                    // TODO: how do we do the conversion here?
                    Role::FirstName => row.first_name = value.into(),
                    Role::LastName => row.last_name = value.into(),
                }
 
                // TODO: needs to emit dataChanged()
                // could we have an existing channel to send signals into?
                // or should developers handle this themselves
                self.model.send(Model::DataChanged{ first, last });
 
                true
            } else {
                false
            }
        }
    }

    impl UpdateRequestHandler<CppObj> for RustObj {
        fn handle_update_request(&mut self, cpp: &mut CppObj) {
           // From a custom channel we could perform signal updates here
            cpp.model_data_changed(first, last);
            cpp.model_rows_inserted(first, last);
            cpp.model_rows_moved(first, last);
            cpp.model_rows_removed(first, last);
            cpp.model_reset();
        }
    }
}
```

**Comment by ahayzen-kdab** [comment]
For setData could return something like Result<Option<Vec<Role>>>, then have a wrapper call the dataChanged.

For the beginInsertRows could use a RAII object to mark the start/end ? Or can we wrap the Vec / impl a way that we can be notified of inserted/changed/removed items in the Vec ?

**Comment by ahayzen-kdab** [comment]
Could store a `std::vector<Row>` on the C++ side like we do for properties. Then we can expose relevant methods to the Rust side eg insert/setData/clear etc.

This has the same limitations/advantages of storing properties on the C++ side rather than Rust side.

**Comment by ahayzen-kdab** [comment]
We could support a "push" rather than "pull" model using a builder pattern.

This has the following advantages
- "safe" as the developer doesn't need to remember to emit signals
- Rust-like as it uses a builder pattern
But has the following disadvantages
- A vector is stored on the C++ side so requires moving of data
- This then means that "infinite" list models can't be done

```rust
cpp.inserter()
    .row(1, Row {})
    .row(2, Row {})
    .insert();

let mut inserter = cpp.inserter();
for (i, item) in items {
    inserter.row(i, item);
}
inserter.insert();
```

Then idea here is that an Inserter object would then do the following
```
// when insert() it then executes
begin_insert_rows(1, 2);
vec.push(row);
vec.push(row);
end_insert_rows();
```

**Comment by LeonMatthesKDAB** [comment]
At this point this probably makes sense to put into a higher-level crate.
