### ISSUE TITLE
Consider which attributes should be on a Q_PROPERTY

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#42]
Have the ability to declare a #[property(getter = "...", setter = "...", notify = "...")]

For example we can't currently say that a property is readonly to C++/QML, but note that this would require the setter to still be accessible from Rust. Does this simply mean which Q_PROPERTY attributes as set?

**Comment by ahayzen-kdab** [comment]
This is being worked on in #451 by @CarlSchwan

**Comment by LeonMatthesKDAB** [comment]
Now being worked on in #994 by @BenFordTytherington

**Comment by LeonMatthesKDAB** [comment]
This is done now
