### ISSUE TITLE
Add docs for enabling git symlinks (originally Repository build fails (Windows))

### ISSUE THREAD

**Issue by uafcybs** [KDAB/cxx-qt#426]
Add documentation that git needs symlinks enabled for Windows otherwise errors occur.

- [ ] Add to README
- [ ] Add to book

# Original description

I've been trying to build "out of the box" repository as suggested in the README file with trivial cmake commands.
It always failed for `cargo_without_cmake` project: 
[build_log.txt](https://github.com/KDAB/cxx-qt/files/10556967/build_log.txt)
Rust - 1.66.1
C++ - MS VS 2022 
CMake - 3.24.3

Are there any other things to consider besides those listed in the README?
Thanks in advance

**Comment by vimpostor** [comment]
I suspect that this is yet another case of Windows line endings ruining the day...
My wild guess is that the problem is in https://github.com/KDAB/cxx-qt/blob/202889fb9d14dc60c724a79a350e4c77abba1b19/crates/cxx-qt-gen/src/syntax/qtfile.rs#L48 where the code finds the end of the line by checking for a Unix line ending.

A workaround would be to setup git to not automatically convert line endings to CRLF (check `git config core.autocrlf`).

Alternatively, could you please test if the following patch fixes the issue?
```diff
diff --git a/crates/cxx-qt-gen/src/syntax/qtfile.rs b/crates/cxx-qt-gen/src/syntax/qtfile.rs
index fa15377..a867215 100644
--- a/crates/cxx-qt-gen/src/syntax/qtfile.rs
+++ b/crates/cxx-qt-gen/src/syntax/qtfile.rs
@@ -45,8 +45,8 @@ pub fn parse_qt_file(path: impl AsRef<std::path::Path>) -> Result<CxxQtFile> {
 
     // We drop the shebang from the generated Rust code
     if source.starts_with("#!") && !source.starts_with("#![") {
-        let shebang_end = source.find('\n').unwrap_or(source.len());
-        syn::parse_str(&source[shebang_end..])
+        let line = source.lines().into_iter().next().unwrap_or(source.as_str());
+        syn::parse_str(&line)
     } else {
         syn::parse_str(&source)
     }
```

**Comment by uafcybs** [comment]
Hi Magnus

Thanks for the answer

The value of core.autocrlf is input.

(I checked files to be sure  – they have 0x0a line endings)

Unfortunately the path did not help as well.

Please let me know if I can do something to find a root cause

Regards

Igor

**Comment by uafcybs** [comment]
In addition to my last email – there are some files with Windows line endings:

*	moc_* files
*	*.h files in vcpgk 

 

Not sure if it’s relevant though

 

Regards

Igor

**Comment by uafcybs** [comment]
Yes, I tried it

Unfortunately – does not help…

**Comment by uafcybs** [comment]
It’s Windows 10. 

Enabling developer mode did not help …

 

Regards

Igor

**Comment by vimpostor** [comment]
> Have you tried the suggested patch?

I realized `find('\n')` would also find the `\n` in `\r\n` and thus work correctly, so it's nothing with line endings after all (hence my deleted comment).
Would need to investigate closer with Windows, I can't see anything now that wouldn't work in Windows at a quick glance.

**Comment by uafcybs** [comment]
No, just “build” folder and repeated both cmake steps…
Gonna try re-clone later . Thanks for the tip!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by uafcybs** [comment]
> > Enabling developer mode did not help …
> 
> Did you delete and re-clone this git repository after enabling developer mode?

Clear/re-clone did not help

**Comment by uafcybs** [comment]
> Make sure Git [has symlinks enabled](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresymlinks) by running `git config core.symlinks true`

This helps, thank you!

**Comment by uafcybs** [comment]
It might be helpful for some other Windows users to mention this symlink related stuff in the README.md.
It is also built out of the box only with `--config Release` in my case. With default (Debug) configuration the build  ends up with lot of linker errors regarding the different debug info levels in object files/libraries.

**Comment by ahayzen-kdab** [comment]
I think it would be a good idea to note this somewhere in the README and/or book so lets re-open this issue to track that.

**Comment by Be-ing** [comment]
> I think it would be a good idea to note this somewhere in the README

I added that to the README here: https://github.com/KDAB/cxx-qt/pull/439
