### ISSUE TITLE
Add qml_module to builder and create qmldir and QML module from build script options

### ISSUE THREAD

**Issue by Be-ing** [KDAB/cxx-qt#434]
Register the qml_module in the build script as we need to produce proper QML modules.

Note that we need to generate a `qmldir`, so for basic ones this will just include the plugin name etc, but if there are QML files included in that module they need to be listed in the `qmldir` too, so we need this to occur in the build script.

So

- [ ] Add `qml_module` to CxxQtBuilder
- [ ] Remove `qml_uri` and `qml_version` from `qobject` macro
- [ ] Add `qml_element` to the `qobject` macro

This could then look like

```rust
#[cxx_qt::qobject(qml_element)
pub struct Thing;
```

```rust
.qml_module("com.foo.bar", 1, 0, |files| {
  files.rs("src/rust/thing.rs");
  files.qml("src/qml/main.qml");
})
```

# Original description
It would be helpful to only need to specify the QML URI and version once in a central place, for example `build.rs`, to avoid repeating this information for multiple QObjects. QObjects exposed to QML could then be indicated with `#[cxxqt::qobject(qml_element)]`.

https://github.com/KDAB/cxx-qt/pull/428#discussion_r1100197053

**Comment by ahayzen** [comment]
I wonder if we should require always specifying `qml_element` or ` qml_singleton` (which implies a `qml_element`) :thinking: 

As when using this it was odd that specifying a uri and version magically made it an element too (and not obvious if that was then a singleton ?)

**Comment by ahayzen-kdab** [comment]
For non-QML related files and resources, eg QObjects or resources exposed to just C++, these would still need to use the old `.file` and `.qrc` methods outside of the `qml_module` callback.

This is fine and can be documented as such, we should just ensure that the API is the same, eg there is `.rs(...)` vs `.file(...)` currently for rust source files should be scanned for a `#[cxx_qt::bridge]`
