### ISSUE TITLE
Use "friend" to avoid leaking protected methods in `#[cxxqt::inherit]`

### ISSUE THREAD

**Issue by LeonMatthesKDAB** [KDAB/cxx-qt#452]
Our current implementation of inheritance (#330) in #363 creates a public method for each inherited protected method.

We could avoid this by marking the CXX Wrapper method as a `friend` of the class.
This would however require us to generate the exact function signature, which may be difficult, especially if we update our CXX version, unless we can get access to CXX's generation somehow.

See: #329

**Comment by ahayzen-kdab** [comment]
We won't be able to get access to it in CXX, i already asked this upstream. They said to put this in a separate crate and then if it's popular they might accept (so we could split this and the C++ type generation into `cxx-qt-utils` or something, see #1144 for that).

So then the question for this becomes which is better
- Marking the protected methods as public, so C++ can see methods it shouldn't, but the generation is easy and always correct
- Using friend to reach the methods, so C++ is correct and can't see the methods, but the generation is harder and could break in the future.

**Comment by LeonMatthesKDAB** [comment]
Blocked by upstream.
