### ISSUE TITLE
`COMMAND_PREIFX` typo error in `CMakeLists.txt`

### ISSUE THREAD

**Issue by OlivierLDff** [KDAB/cxx-qt#467]
Hi I guess it should be `COMMAND_PREFIX` even if it won't affect a thing.

https://github.com/KDAB/cxx-qt/blob/e9fde3e95fd340a6a977a64abeb2ac335f3d5de7/CMakeLists.txt#L38

**Comment by Be-ing** [comment]
That's intentional. What's the problem?

**Comment by Be-ing** [comment]
oh, I see, it's the typo in the variable :upside_down_face:
