### ISSUE TITLE
Need to be able to choose the parent when deriving from different bases

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#474]
Currently we assume that it'll be `QObject* parent = nullptr`, but for some Qt types (eg QQuickPaintedItem or QQuickItem) the parent is different.

We need to have a way in the `cxx_qt::qobject` macro to be able to specify a different parent other than `QObject`.

There seems to be these options

- If we can assume all parent types will be a raw pointer then just have `#[cxx_qt::qobject(base = "QQuickPaintedItem", parent = "QQuickItem"]`
- If we can't assume this then we might need something like `#[cxx_qt::qobject(base = "QQuickPaintedItem", parent_ptr = "QQuickItem"]` or `#[cxx_qt::qobject(base = "QQuickPaintedItem", parent = "QQuickItem*", parent_default = "nullptr"]`
- Have a separate macro for items that aren't directly derived from `QObject`, eg have `#[cxx_qt::qquickitem(base = "QQuickPaintedItem")]` this then means that we can generate the different asserts and parent etc and it's clear to the developer which base the type is deriving from

**Comment by LeonMatthesKDAB** [comment]
Could this be fixed by specifying our own constructor API :thinking: : https://github.com/KDAB/cxx-qt/discussions/339

Would be a more general solution to the problem, right?

**Comment by ahayzen-kdab** [comment]
Potentially :thinking: 

So we then might have to get the following things into the same constructor feature
- Picking a different parent type
- Triggering code in the context of C++ from the constructor
- How do we represent that `QObject* parent` has a default value of `nullptr` ?
- Adding more args to the constructor (what happens with QML here though?)

**Comment by ahayzen-kdab** [comment]
We could make `Option<*mut T>` mean that it is a pointer that defaults to `nullptr`, but slightly odd syntax :thinking:

**Comment by ahayzen-kdab** [comment]
I've created an experiment in #513 of using the attribute route for the `parent` as the constructor route is much more complex. This then allows you to choose a different parent then allowing you to create a `QQuickPaintedItem` in Rust with no C++ :-)

**Comment by LeonMatthesKDAB** [comment]
Closing this in favor of #550
