### ISSUE TITLE
Cross-compilation support

### ISSUE THREAD

**Issue by machitgarha** [KDAB/cxx-qt#483]
I couldn't find anything in the docs; is there any support for cross-compilation? Like compiling on Linux for Windows (x86_64).

**Comment by Be-ing** [comment]
That hasn't been tested, but if you run into any issues with that, please let us know.

**Comment by Be-ing** [comment]
@LeonMatthesKDAB has built with CXX-Qt for ARM Yocto. I think he did it from a Fedora Linux x86-64 host, but I'm not sure.

**Comment by LeonMatthesKDAB** [comment]
I was using a docker Ubuntu as the host, but yes, you can cross-compile for ARM yocto with a reasonable amount of effort.

If you wanto to build your own yocto image with a CXX-Qt application, you can take inspiration from:
https://github.com/leonmattheskdab/cxx-qt-demo
and:
https://github.com/leonmattheskdab/cxx-qt/tree/yocto-kirkstone

**Comment by ahayzen-kdab** [comment]
Was the first link supposed to be https://github.com/LeonMatthesKDAB/meta-cxx-qt-demo ?

**Comment by machitgarha** [comment]
@ahayzen-kdab, also doesn't work.

**Comment by ahayzen-kdab** [comment]
Ah looks like they are private repos, we'll see if they can be opened up when Leon is back :-)

**Comment by LeonMatthesKDAB** [comment]
Hi @machitgarha , sorry for the delay, was on vacation until now.

I've made https://github.com/LeonMatthesKDAB/meta-cxx-qt-demo public.
Will check the other repo (https://github.com/leonmattheskdab/cxx-qt-demo) to make sure the licenses check out, should be able to make it public then as well.

**Comment by LeonMatthesKDAB** [comment]
Ah, wait nevermind, you don't need the "cxx-qt-demo" repo anymore.
I've moved all code for that into: https://github.com/leonmattheskdab/cxx-qt/tree/yocto-kirkstone
Under the `examples/demo_threading` folder.

**Comment by LeonMatthesKDAB** [comment]
Experience from both Yocto builds, as well as Android cross-compilation (#549 ) has shown that cross-compilation should work with normal cross-compilation tooling for Rust&CMake, possibly requiring minor changes for a specific setup.

Therefore I will close this issue.

In case anyone experiences a specific issue, feel free to report it.
