### ISSUE TITLE
book: it is unclear how qt version is found on first read

### ISSUE THREAD

**Issue by OlivierLDff** [KDAB/cxx-qt#492]
Hi,
I'm trying qml-minimal example on my machine. My background is I'm very familiar with Qt & CMake, but not that much with rust.

From first read, it was unclear to me how the Qt version was found on rust side.
It would have been nice to mention it in https://github.com/KDAB/cxx-qt/blob/92feeae6bd29ad0ed852c8953fd247c3f0a274d4/book/src/getting-started/4-cmake-integration.md?plain=1#L35-L37 that `qmake -query` was used for configuration.

Same here: https://github.com/KDAB/cxx-qt/blob/92feeae6bd29ad0ed852c8953fd247c3f0a274d4/book/src/getting-started/4-cmake-integration.md?plain=1#L79

"Will be used later" is not clear, why?

When you go thru the example it make sense, but that wasn't that obvious in the beginning.

What do you think?

**Comment by Be-ing** [comment]
Feel free to open a PRs for the documentation. Maybe something like "From the Qt CMake target, find the location of the qmake executable. cxx-qt-build will need this to find Qt." ?

**Comment by OlivierLDff** [comment]
What do you think about:

```markdown
We'll have to do multiple things:
- Instruct cargo to create a staticlib
- Add `cxx`, `cxx-qt`, as well as `cxx-qt-lib` as dependencies
- Add `cxx-qt-build` as a build dependency

Note that in order for cxx-qt to work, the qmake executable must be located. This is because cxx-qt relies on qmake to locate the necessary Qt libraries and header files on your system. This can be done by either adding it to your system's PATH, or by setting the `QMAKE` environment variable to its path.

To check which version of Qt will be used with `qmake`, you can use the `qmake -query` command. This will display information about the Qt installation, including the version number and installation path.
```

And then in the CMake section
```markdown
To ensure that cxx-qt-build uses the same version of Qt as your CMake targets, you can use the `Qt` CMake target to locate the qmake executable. The `qmake` executable will be pass to `build.rs` as an environment variable using `corrosion_set_env_vars`.
```

When I first followed the tutorial, I tried to run a `cargo build` even before starting to read the CMake section.
So we we could add at the end of the cargo section something like:

```markdown
> At this point, you can test your library build by running `QMAKE=/path/to/qmake cargo build` inside the `rust` folder. This should output a static library in `rust/target/debug/qml_minimal.lib` on Windows or `rust/target/debug/qml_minimal.a` on Unix system.
```
If you approve the change, I will push that in a PR
