### ISSUE TITLE
Is there a drawback to always calling `qt_build_utils::setup_linker` ?

### ISSUE THREAD

**Issue by OlivierLDff** [KDAB/cxx-qt#508]
It is just shown in the `build.rs` for cargo only, without any explaination. 
Digging in the code I found the reason why (and of course I had my linking failing due to not calling it, doing a `cargo build`).

Is it a problem to always call this function, even if linking will be done by CMake?

**Comment by Be-ing** [comment]
This is documented at https://docs.rs/qt-build-utils/latest/qt_build_utils/fn.setup_linker.html but we should probably mention it in a more obvious place too.

**Comment by OlivierLDff** [comment]
Yes I've found the documentation, my question is what happen if it is called in a `build.rs` that is built by CMake ?

**Comment by Be-ing** [comment]
AFAIK it shouldn't matter because CMake invokes the linker in that case.

**Comment by ahayzen-kdab** [comment]
If it has no side affects for CMake builds then why don't we just call this in `CxxQtBuilder::build()` so that the developer doesn't need to know about this workaround for Linux ?

I'll create a pull request to try this out ...

**Comment by Be-ing** [comment]
>  why don't we just call this in CxxQtBuilder::build()

Because nobody thought to do that before :)
