### ISSUE TITLE
cxx-qt: corrosion error while building qml-minimal example

### ISSUE THREAD

**Issue by zyend36** [KDAB/cxx-qt#516]
I'm currently trying to build the qml-minimal example from the cxx-qt book.
Everything looks fine until I try to build the main `CMakeLists.txt` file.

I have the following error:

```
Make Error at /usr/local/share/cmake/CorrosionGenerator.cmake:205 (message):
  found no targets in 42 packages
Call Stack (most recent call first):
  /usr/local/share/cmake/Corrosion.cmake:1120 (_generator_add_cargo_targets)
  CMakeLists.txt:44 (corrosion_import_crate)
```
I have never used corrosion-rs and I don't understand this error and how to solve it.
I have tried to intall corrosion-rs seperatly....but I get the same error.

Any suggestion would be welcome.
Cheers.

**Comment by zyend36** [comment]
> Have you tried using ninja as generator?

No I haven't. 
I've no clue how to replace it with Ninja in the given example :(

**Comment by OlivierLDff** [comment]
Install ninja, then `cmake -G Ninja`.

**Comment by ahayzen-kdab** [comment]
Also if you could provide the output of what commands you are running and in which folders. As it might be useful to check that those are correct or if there is something we should be more explicit in the docs with.

**Comment by ahayzen-kdab** [comment]
FWIW, i just tried following the tutorial and got this output. I've used Qt 5.15 in this case, but don't think that should matter.

Maybe there is some other subtle difference.

<details>

<summary>Code output</summary>
```
$ cmake -S . -B build
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at CMakeLists.txt:12 (find_package):
  By not providing "FindQt6.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt6", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt6" with any of
  the following names:

    Qt6Config.cmake
    qt6-config.cmake

  Add the installation prefix of "Qt6" to CMAKE_PREFIX_PATH or set "Qt6_DIR"
  to a directory containing one of the above files.  If "Qt6" provides a
  separate development package or SDK, be sure it has been installed.


-- Rust Toolchain: stable-x86_64-unknown-linux-gnu
-- Rust Target: x86_64-unknown-linux-gnu
-- Found Rust: /var/home/andrew/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc (found version "1.68.0") 
-- Using Corrosion as a subdirectory
    Updating crates.io index
 Downloading crates ...
  Downloaded cxx-build v1.0.94
  Downloaded thiserror-impl v1.0.40
  Downloaded cxxbridge-macro v1.0.94
  Downloaded cxxbridge-flags v1.0.94
  Downloaded thiserror v1.0.40
  Downloaded syn v2.0.15
  Downloaded cxx v1.0.94
  Downloaded libc v0.2.141
  Downloaded cxx-qt-lib-headers v0.5.1
  Downloaded cxx-qt-build v0.5.1
  Downloaded qt-build-utils v0.5.1
  Downloaded cxx-qt-gen v0.5.1
  Downloaded cxx-qt v0.5.1
  Downloaded cxx-qt-lib v0.5.1
  Downloaded cxx-gen v0.7.94
-- Configuring done
-- Generating done
-- Build files have been written to: /var/home/andrew/Projects/cxx-qt/tutorial/build
```

</details>

**Comment by ahayzen-kdab** [comment]
Aha so in my `Cargo.toml` if i remove this part then i get a similar looking error to you. Are you able to post your `Cargo.toml` maybe this was missed ?

```toml
[lib]
crate-type = ["staticlib"]
```

**Comment by zyend36** [comment]
> Aha so in my `Cargo.toml` if i remove this part then i get a similar looking error to you. Are you able to post your `Cargo.toml` maybe this was missed ?
> 
> ```toml
> [lib]
> crate-type = ["staticlib"]
> ```

Below the content of my Cargo.toml

```
package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


# This will instruct Cargo to create a static
# library which CMake can link against
[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0.83"
cxx-qt = "0.5"
cxx-qt-lib = "0.5"

# cxx-qt-build generates C++ code from the `#[cxx_qt::bridge]` module
# and compiles it together with the Rust static library
[build-dependencies]
cxx-qt-build = "0.5"

```

**Comment by ahayzen-kdab** [comment]
Ah, so i see what has happened. The crate name is different, you've changed `name = "qml-minimal"` to `name = "rust"` in the `Cargo.toml.

If you look at this section of the `CMakeLists.txt` you'll notice it is specifying the crate name as `qml-minimal`

```cmake
set(CRATE qml-minimal)
# Corrosion creates a CMake target with the same name as the crate.
corrosion_import_crate(MANIFEST_PATH rust/Cargo.toml CRATES ${CRATE})
```

So if you change this to `set(CRATE rust)` it should work or change your crate name back to `qml-minimal` as they need to match :-)

**Comment by zyend36** [comment]
> 
I just realized I've created the lib with cargo --lib rust and forgot to change the package name..
Thanks for your quick feedback !
Issue is solved ;)

**Comment by zyend36** [comment]
Issue is solved.
