### ISSUE TITLE
Consider allowing `#[doc]` in `cxx_qt::inherit` blocks

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#532]
In #518 we start generating docs for any methods that are inherited, but instead we should consider if supporting passing through documentation instead and require the developer to document their inherit methods.

Currently if one tries to do this our generator states that the doc attribute is not supported.

**Comment by ahayzen-kdab** [comment]
I think the problem with doing this will be that when the dev doesn't add the doc line and they have deny(missing_docs) enabled the error won't be obvious as it states that an associated function (one we generate in the macro) is missing the doc, not the original one from the inherit block.

**Comment by ahayzen-kdab** [comment]
We now allow passing through doc lines, but we should ensure that this is still the case after the new API with all the methods and types in the CXX blocks should be documented as usual.

**Comment by LeonMatthesKDAB** [comment]
Done as of #1054
