### ISSUE TITLE
QVariantMap

### ISSUE THREAD

**Issue by ChrisCochrun** [KDAB/cxx-qt#533]
The cxx-qt-lib appears to not have a QVariantMap. However, it does have a QMap-QString-QVariant. Which I can use, but since it is not recognized as a QVariantMap in QML, it must first pass through C++ before QML can pick it up. I've worked around this with a C++ bridge that passes the params to rust functions and the returned QMap-QString-QVariant back to QML as a QVariantMap and QT seems to do the conversion automatically since it's just an alias for the same thing.

Any idea why Rust can't send those back to QML without first going through C++?

**Comment by ahayzen-kdab** [comment]
The error the occurs is `QMetaProperty::read: Unable to handle unregistered datatype 'QMap_QString_QVariant' for property 'MyObject::test'`.

Changing `QMap_QString_QVariant` to `QVariantMap` in `cxx-qt-lib` solves the problem, but i see multiple options for the solution to this

- Correctly register `QMap_QString_QVariant` as a type to Qt/QML, and see if that is able to figure out it is the same as `QVariantMap`
- Rename `QMap_QString_QVariant` to `QVariantMap` (and same for `QVariantHash` etc), but this would need to be in 0.6
- Add a new type `QVariantMap` alongside `QMap_QString_QVariant`, but this would slow the compilation speed of `cxx-qt-lib` further

**Comment by ahayzen-kdab** [comment]
OK first option also works.

Adding this to a C++ header that is included also solves the problem and could be used as a workaround until we merge a fix / backport it.

```cpp
static const int qvariantmap = qRegisterMetaType<QMap_QString_QVariant>("QMap_QString_QVariant");
```

**Comment by ahayzen-kdab** [comment]
So #534 should solve this for `QVariant{Hash,List,Map}` hopefully, if you could try this out by pointing your Cargo manifest to that branch rather than crates.io to see if it solves your issue that'd be useful :-)

**Comment by ChrisCochrun** [comment]
Well there we go! It works just as I thought it should! I've only tested for QVariantMap, not List or Hash yet, but I didn't have to change anything. Thanks!

**Comment by ahayzen-kdab** [comment]
@ChrisCochrun FYI this has now been backported to `0.5.3`, please let us know if you have any further issues or suggestions in new issues :-)
