### ISSUE TITLE
rust-analyzer displays "variable doesn't need to be mutable"

### ISSUE THREAD

**Issue by LeonMatthesKDAB** [KDAB/cxx-qt#537]
![image](https://github.com/KDAB/cxx-qt/assets/84974957/fcee9eb0-3e44-4101-bce7-40d9c189b13b)

Cause is unknown atm.

**Comment by ahayzen-kdab** [comment]
Does it do it for all files or only certain places like the invokables example ? As could be something in our generation or CXX generation ?
