### ISSUE TITLE
Add member functions to basic Qt types in Rust

### ISSUE THREAD

**Issue by LeonMatthesKDAB** [KDAB/cxx-qt#55]
- [x] Add missing member functions to types #416
- [ ] Consider if we should adapt the Rust API to be "safe" / less Qt-like (eg QRectF set_x)

Original Description
Types like QPoint have a lot of member functions, as well as operators (i.e. +,-,/,*) that make them a lot more useful. We should give Rust access to these as well.

**Comment by ahayzen-kdab** [comment]
Note that this is related to #53

**Comment by LeonMatthesKDAB** [comment]
Note: QRect's interface should propably *not* mimic Qt directly. set_x and set_y will change the width and height, which is not at all obvious/expected behavior. So we should improve on Qt in this regard, and come up with our own, safer interface.

**Comment by ahayzen-kdab** [comment]
Also ensure that we are using CXX where we can. 

Eg
```rust
#[rust_name = "qurl_to_qstring"]
fn qurlToQString(url: &QUrl) -> QString;
```

could probably just be

```rust
#[rust_name = "to_string"]
fn toString(self: &QUrl) -> QString;
```

**Comment by ahayzen-kdab** [comment]
Also note that `QDateTime` it would be useful to link up the static methods like `QDateTime::currentDateTime()`, otherwise might have static methods that could be useful too.

**Comment by ahayzen-kdab** [comment]
Closing via #416.
