### ISSUE TITLE
Remove Reliance on the sizeof(int), etc.

### ISSUE THREAD

**Issue by LeonMatthesKDAB** [KDAB/cxx-qt#57]
For the conversion of some types, we currently rely on the fact that sizeof(int) is 32 bit wide on most platforms.
Unfortunately, according to the C and C++ standards, this doesn't have to be the case. There might already exist platforms where an "int" is 64 bits wide.

Therefore instead of checking that an int is 32-bit wide, maybe the appropriate action is to change the data type we're using for the Rust side depending on the size of int.

We should probably also look into how CXX deals with this :thinking:

**Comment by ahayzen-kdab** [comment]
Can we just use `std::int8_t`, `std::int16_t` etc as we did this elsewhere :thinking:  But then is the problem that "int" in a Qt object might sometimes be a int32 or int64 or whatever :thinking:

**Comment by ahayzen-kdab** [comment]
All the sizeof's now uses int32 etc and we check that it matches the Qt object.
