### ISSUE TITLE
Once API changes are done improve the book and documentation

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#582]
Ensure that the documentation covers the new API correctly in all places.

Also consider reordering the book topics to be the same as CXX's book, which has

- Core Concepts (general concept)
- Tutorial (the current tutorial)
- Comparison with other tools (qmetaobject-rs etc)
- Build system options (CMake vs cargo for us)
- Reference the bridge
  - extern "Rust" (RustQt for us)
  - extern "C++" (C++Qt for us)
  - attributes
  ...
- reference: built-in bindings
  - we would have
    - cxx-qt-lib 
    - threading
    - locking
    - CxxQtType
    - another other traits etc

**Comment by LeonMatthesKDAB** [comment]
Mostly done now. Documentation is an ongoing task
