### ISSUE TITLE
Cargo only example fails in `main` with Qt 5 due to std types confusion

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#592]
```bash
$ cargo run -p qml-minimal-no-cmake
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/qml-minimal-no-cmake`
QQmlApplicationEngine failed to load component
qrc:/main.qml:26:17: Invalid property assignment: unsupported type ""
```

Using `main` the cargo-only build fails to run with Qt 5 due to `std_types.cpp` not occurring, it however works with CMake.

This is likely due to `+whole-archive` missing ?

**Comment by Be-ing** [comment]
Oof, I hadn't noticed this because we default to using Qt6. I wonder when this bug was introduced?
