### ISSUE TITLE
Explore using Fn/FnOnce trampolines for queuing onto CxxQtThread and for signal connections

### ISSUE THREAD

**Issue by LeonMatthesKDAB** [KDAB/cxx-qt#595]
See: https://github.com/dtolnay/cxx/issues/668

In the above discussion this approach is linked: https://adventures.michaelfbryan.com/posts/rust-closures-in-ffi/
It may save us from having to do so much heap-allocation and wrapping for executing closures in the cxx-qt-thread.
So explore if this is feasible and which (dis-)advantages it brings.

Ideally we could also use this approach to allow closures when connecting to signals.

**Comment by ahayzen-kdab** [comment]
We also need to allow for closures (FnMut) in signal connections. Otherwise you cannot move a binding into the closure to use in the connection. Eg the following doesn't work.

```rust
let qt_thread = self.qt_thread();
anotherObject.on_signal(|ctx| {
  // cannot move the qt_thread here
  // as the on_signal is just a function ptr ( fn )
  // instead of a closure ( FnMut )
  qt_thread.queue(|ctx| { ... });
});
```
