### ISSUE TITLE
Determine if passing through foreign funcs is worth it

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#616]
We can potentially pass through the input of certain items to the output with minimal modification

- [ ] Invokables
- [ ] Signals
- [ ] Inherit

Determine if it is worth it to simplify the parser or not, for signals #615 shows that this may not be worth the effort as there are other methods that need to be generated anyway and the method still needs extra attributes added to it.

**Comment by LeonMatthesKDAB** [comment]
We've now gone the following route:

We never modify the input, but we still always fully reconstruct the output ourselves and never pass anything through.
This gives us certainty about our possible outputs so should be more stable and maintainable down the line.
