### ISSUE TITLE
cxx-qt-lib bindings for QAnyStringView

### ISSUE THREAD

**Issue by Be-ing** [KDAB/cxx-qt#629]
[QAnyStringView](https://doc.qt.io/qt-6/qanystringview.html) is a new class in Qt6 that is being used in new Qt APIs that take string arguments, for example [QQmlApplicationEngine::loadFromModule](https://doc-snapshots.qt.io/qt6-6.5/qqmlapplicationengine.html#loadFromModule). It supports UTF-8 strings, so it may be possible to implement cheap conversion from Rust &str to QAnyStringView without needing to copy data or convert to UTF-16 for a QString first.

**Comment by ahayzen-kdab** [comment]
We only pass in the major Qt version at the moment and the QQmlApplicationEngine method is since a minor version.

I'm going to look at exposing Qt major, minor, micro versions to the app developer as well, so I'll combine that into one change :-)
