### ISSUE TITLE
Inconsistent naming convention on QGuiApplication

### ISSUE THREAD

**Issue by Billyzou0741326** [KDAB/cxx-qt#652]
This is more of a question on the naming convention.

Is there a reason why this particular function doesn't take the shorter name, `set_organization_domain` (line 167)?

https://github.com/KDAB/cxx-qt/blob/e91a4edab05a00680ea9ba82594d5f361fb00a38/crates/cxx-qt-lib/src/gui/qguiapplication.rs#L166-L169

Using this function comes out to be something like `app.qguiapplication_set_organization_domain(...);`. It personally feels a bit too verbose.

I saw a few other similar functions take the shorter name, `set_xxx` instead of `qguiapplication_set_xxx`,

https://github.com/KDAB/cxx-qt/blob/e91a4edab05a00680ea9ba82594d5f361fb00a38/crates/cxx-qt-lib/src/gui/qguiapplication.rs#L150-L164

https://github.com/KDAB/cxx-qt/blob/e91a4edab05a00680ea9ba82594d5f361fb00a38/crates/cxx-qt-lib/src/gui/qguiapplication.rs#L171-L174

**Comment by ahayzen-kdab** [comment]
Thanks for taking the time to report this issue and make CXX-Qt better.

Oops, looks like this was a copy and paste / typo that hasn't been spotted until now, it should be with the shorter name as you suggest, I'll fix it :-)

**Comment by ahayzen-kdab** [comment]
Fix can be found in #653
