### ISSUE TITLE
Consider if we can allow sub object to be returned

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#66]
Currently nested objects can be used as properties and parameters. But they cannot be used as return types as we need return a pointer on the C++ side, but also ensure that the ownership is in a valid place (?). Eg we can't construct a sub object inside an invokable and then return it, as no one owns it.

**Comment by LeonMatthesKDAB** [comment]
Hm, if we pass pointers to things from C++ <-> Rust, we will definitely have to make ownership explicit.
So maybe use unique_ptr <-> Box and shared_ptr <-> (A)rc.

But that would open it's own can of worms, especially because mutability is still very different between a shared_ptr and an Rc.

**Comment by ahayzen-kdab** [comment]
Merged into #299
