### ISSUE TITLE
Support for private signals

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#661]
We need to consider how to support private signals, this works by adding a dummy `QPrivateSignal` to the last value of the signal. Which then means that you can only connect and not emit these signals.

https://woboq.com/blog/how-qt-signals-slots-work-part2-qt5.html
https://codebrowser.dev/qt5/qtbase/src/corelib/itemmodels/qabstractitemmodel.h.html#_ZN18QAbstractItemModel21rowsAboutToBeInsertedERK11QModelIndexiiNS_14QPrivateSignalE

- [x] Decide on an API to support these
- [x] Do not generate the emit method for extern "C++Qt" signals
- [x] Decide if and what happens to signals in extern "RustQt" ?

**Comment by LeonMatthesKDAB** [comment]
Suggested API using `pub(self)` as the visibility.
```rust
    unsafe extern "C++Qt" {
        type QFileSystemWatcher;

        #[qsignal]
        pub(self) fn file_changed(self: Pin<&mut QFileSystemWatcher>, ...);
    }

**Comment by LeonMatthesKDAB** [comment]
As the [Rust docs](https://doc.rust-lang.org/reference/visibility-and-privacy.html) state:

> pub(self) makes an item visible to the current module.
> This is equivalent to pub(in self) or not using pub at all.

So this would be eqiuvalent to "not using pub at all", which is the closest thing Rust has to "private".
We could use this semantic to explicitly overwrite CXX default, which defaults everything to `pub`.

**Comment by ahayzen-kdab** [comment]
Not going to implement on RustQt for now, as it doesn't really gain us much vs the generation required.
