### ISSUE TITLE
Qt Widget support

### ISSUE THREAD

**Issue by FynnFbc** [KDAB/cxx-qt#692]
Can you configure Qt Widget? No documentation has been found. Please provide a solution

**Comment by ahayzen-kdab** [comment]
In theory you can use normal CXX bridges to create bindings to Qt widgets objects with 0.5.x.

However for 0.6.x we are making it easier to define bridges for external Qt types.

Eg in theory this will work with 0.6

```rust
    unsafe extern "C++Qt" {
        include!(<QtWidgets/QPushButton>);
        type QPushButton;

        fn setText(self: Pin<&mut QPushButton>, text: &QString);

        #[qsignal]
        fn clicked(self: Pin<&mut QPushButton>, checked: bool);
    }
```

Then once we have that and we have other changes we may be able to start adding some QtWidgets types as bindings to cxx-qt-lib more easily.

However note that a lot of the Qt widgets API is pointer driven which isn't too suited to CXX and Rust as it results in unsafe code, so it is probably generally beneficial to keep the UI driven from C++ and have Rust provide the models to the UI layer (eg through QAbstractitemModels etc).

**Comment by FynnFbc** [comment]
How do I import main.ui window files and bind events to part objects

**Comment by ahayzen-kdab** [comment]
For now you need to do that in C++, CXX-Qt has been primarily focused on getting QML to work well so far and also providing the ability to create models. These models can then be used like normal in C++ with widgets. No one has really tried widgets yet or added the features for it.

**Comment by ahayzen-kdab** [comment]
Note that it is likely possible to create your own CXX bindings for the relevant methods, but it is sometimes simpler for now to drop to C++ for the UI layer.
