### ISSUE TITLE
Auto-generate boilerplate for unique-ptr wrapper functions

### ISSUE THREAD

**Issue by LeonMatthesKDAB** [KDAB/cxx-qt#72]
The `cxx-qt-gen/src/cxx_qt.cpp` file must create a C++ wrapper function for every function we want to use on an opaque type on the Rust side.

That requires a lot of boilerplate code that should be automated.

**Comment by ahayzen-kdab** [comment]
#105 will close this.

**Comment by ahayzen-kdab** [comment]
This has been changed now, and most types aren't opaque anymore :tada:
