### ISSUE TITLE
Emitting a signal consumes self - how to send two signals in one function?

### ISSUE THREAD

**Issue by mmMike** [KDAB/cxx-qt#728]
The title says it all, it seems not very convenient that sending a signal consumes self.

The signal is defined like this

    unsafe extern "RustQt" {
        #[qinvokable]
        fn say_hi(self: Pin<&mut MyObject>);

        #[qsignal]
        fn signal(self: Pin<&mut MyObject>, data: &QString);
    }

And emitted like this

    pub fn say_hi(self: Pin<&mut Self>) {
        self.signal(&QString::from("Hi"));
    }

Since self is consumed no work can be done with self after sending the signal and no second signal can be sent.

Is there a way around that?

**Comment by LeonMatthesKDAB** [comment]
Hi @mmMike ,
cool to hear you're interested in CXX-Qt :)

Yes, there is indeed a way around this.
[`Pin::as_mut`](https://doc.rust-lang.org/std/pin/struct.Pin.html#method.as_mut) allows you to create another `Pin<&mut Self>` that you can then call `signal` on without losing the original one.

So the code would look like this:
```rust
// Notice the additional `mut` here
//            vvv
pub fn say_hi(mut self: Pin<&mut Self>) {
    self.as_mut().signal(&QString::from("Hi"));
    // Do something else with `self`
}
```

This is a bit of unfortunate boiler-plate, but a natural side-effect from the way pinning works in Rust.
Often a Pin doesn't actually use `Pin<&mut Self>`, but rather something like `Pin<Box<Self>>`. In that case for every call that needs a `Pin<&mut Self>` you would construct a new mutable reference to the inner object using `Pin::as_mut` when calling a mutable function.
I think that explains a bit better why the approach taken by the Rust stdlib team is necessary.

If you already have a `Pin<&mut Self>` it's a bit weird though to have to call `as_mut()` all the time.
And as you've already noticed you can omit the `as_mut()` call on the last call that takes `Pin<&mut Self>`, as that can  consume the Pin.

We would love to get rid of this boilerplate in future, but it's currently something we have to deal with as even the standard library doesn't have a better solution.
