### ISSUE TITLE
Allow to create #cfg for adding specific method in qt6 or qt5

### ISSUE THREAD

**Issue by Montel** [KDAB/cxx-qt#765]
Hi,
Qt5 and Qt6 must have new methods or method removed.
We must be able to use a #cfg(...) for adding it in specific qt_version_major

Idea is using specific mod

For example:
#[cfg(qt_version_major = "6")]
#[cxx::bridge]
mod ffi_qt_6 {
...
}

At the moment it doesn't build ad it seems that qt_version_major  is not forwarded by the build system.

We really need to add it if we want to support new qt6 methods.

**Comment by ahayzen-kdab** [comment]
Note that once we have #840 we might be able to do something in our own macro to include / exclude methods via a macro / feature / version detection etc.

**Comment by ahayzen-kdab** [comment]
So CXX supports cfg attributes, but in `cxx_gen` the `cfg_evaluator` is private https://github.com/dtolnay/cxx/blob/1fd8a5fcaa7ea97532c58f4c9320989d63451f6b/gen/src/mod.rs#L61 So we need a way to reach this.
