### ISSUE TITLE
Investigate behavior of object references in extern "C" code

### ISSUE THREAD

**Issue by LeonMatthesKDAB** [KDAB/cxx-qt#77]
Currently we sometimes declare `extern "C"` functions in C++ that take references as arguments.

As references aren't part of the C language, it's unclear what exactly this code compiles down to. Currently, this doesn't seem to cause issues under GCC, Clang or MSVC, but it is likely compiler dependent.

This is a tracking issue to reference, should this issue come up in the future.
We will not change our code for now, as CXX also uses references in this way, so CXX would need to be changed anyway.

**Comment by ahayzen-kdab** [comment]
We don't have any `extern "C"` blocks left for now ? They might come back with container classes in #291 but for now this issue can be closed.
