### ISSUE TITLE
Add CI for using Windows with msvc

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#79]
Github Actions supports using Windows as the machine, add a CI definition which supports this ( https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources )

- [ ] msvc
- [ ] Rust (cargo, clippy, rustfmt, rustc) (also mdbook and mdbook serve eventually)
- [ ] Qt 5.15 / Qt 6.2
- [ ] clang-format
- [ ] cmake
- [ ] reuse
- [ ] ~~valgrind~~ (would need to disable these tests)

**Comment by ahayzen-kdab** [comment]
We also need to see what fails to build on Windows :-)

**Comment by Be-ing** [comment]
I have experience setting up GitHub Actions for a [Qt project](https://github.com/mixxxdj/mixxx) for Windows & macOS using vcpkg. vcpkg works nicely with caching the built packages on GitHub Packages, which is free for public repositories. Would this be a welcome approach to implementing this?

**Comment by ahayzen-kdab** [comment]
@Be-ing sure that'd be really useful ! 

Note that we know that this is unlikely to build and run on Windows as no one has tried it there yet and there is some CMake specific to UNIX-like OSes that will need to be tweaked :-) So don't worry about the project itself not building we need to go through and get that working anyway.

But if you were able to create a pull request to show us what the equivalent of our Linux action would be for Windows ( https://github.com/KDAB/cxx-qt/blob/main/.github/workflows/github-cxx-qt-tests.yml ) that'd be awesome! :-)

**Comment by Be-ing** [comment]
Fixed by #107
