### ISSUE TITLE
Transparently use the CppObjWrapper in invokables and other methods

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#8]
Currently we have `cpp: Pin<&mut CppObj>` as the type to signify the Cpp instance. This works until you try to perform multiple mutations, and doesn't allow us to perform the Rust <-> C++ conversions transparently. This also means users can perform tasks that might be considered "unsafe" - eg triggering an invokable via the C++ side rather than Rust (could cause deadlock).

Currently users need to write `let wrapper = CppObjWrapper::new(cpp);` and then user this wrapper.

Instead use something like `cpp: CppObj` or `cpp: CppObjWrapper` as the type the user uses, then transparently generate another rust method which is called first and takes the `Pin<&mut CppObj>`, then creates the wrapper and calls the users method.

**Comment by ahayzen-kdab** [comment]
Potentially use `Cpp<T>` as the type to the user, then transparently swap for `Pin<T>` and `CppObjectWrapper` ?

This would end up as

- Current module `Cpp<&mut MyObject>` -> `std::pin::Pin<&mut CppObj>` -> `&mut CppObjectWrapper`
- Sub object / external module `Cpp<&mut crate::sub_object::SubObject>` -> `std::pin::Pin<&mut crate::sub_object::CppObj>` -> `&mut crate::sub_object::CppObjectWrapper`

It potentially allows for removing Pin as a QtType in the extract phase ?

**Comment by LeonMatthesKDAB** [comment]
`Cpp<&mut MyObject>` sounds like a good type to aim for in the API. However, I have a few questions about the types involved here:

1. Where does the `MyObject` type come from? Currently the "QObject" of class "MyObject" in rust is described by a module, not by a single struct, so what is this type?
    - If this broadly refers to the QObject, it could also just be `Cpp<&mut Data>`, as the Data struct is where the user is actually describing the data stored in the QObject. And this data is what the `Cpp<>` object is wrapping if I understand it correctly.
2. Why would the `Cpp` type have to swap between the Pin and the `CppObjectWrapper`?\
Couldn't we just hand the `CppObjectWrapper` directly to any `#[invokable]` function of the RustObject? What can the Pin do that the CppObjectWrapper can not do?

**Comment by ahayzen-kdab** [comment]
Right `MyObject` comes from the generated `ffi::MyObject` (which in this module has an alias of `CppObj` as well). Yes it is effectively pointing to which QObject we are going to wrap, the Data struct is interesting, as the wrapper has getter/setter methods but not invokables. The question then becomes what do other external modules look like ? As i was thinking `Cpp<&mut crate::another_object::AnotherObject>` for that, but would that instead be `Cpp<&mut crate::another_object::Data>` ? :thinking:
Do note that the wrapper also provides a method to reach the update requester for the QObject to trigger events on the GUI thread.

For the `CppObjWrapper`, we need to create that on the Rust side, so when C++ calls the Rust invokable it uses `Pin<T>`. The idea here is that we auto generate a wrapper method that takes `Pin<T>`, this method creates the `CppObjWrapper` and then calls the invokable the user has specified. So the user would only see `Cpp<&mut MyObject>` switch to `CppObjectWrapper`, or they would see `Cpp<&mut crate::another_object::AnotherObject>` to `crate::another_object::CppObjectWrapper`.

**Comment by ahayzen-kdab** [comment]
Using the module name itself might be a possibility, as you don't always have the `Data` struct. So this could end up as

- `Cpp<&mut my_object>` for a Cpp inside the `my_object` module
- `Cpp<&mut crate::another_object>` for referring to another object

Should the module names always be full qualified ? (eg `crate::my_object` instead of a magic `my_object`) Or is there a keyword to mean the current module, similar to `super` ? Or could we just call that `self` ?

**Comment by ahayzen-kdab** [comment]
So I think it should be `Cpp<T>` where `T` is a module path. Then either it can be a qualified path such as `crate::*` or `super::*` or `::*` but if it starts with a freeform name such as `my_object` then we inject `super::` as a prefix.

This then results in the user using `Cpp<&mut crate::another_object>` or `Cpp<&mut my_object>`, and the generation then can use `super::my_object::N` or `crate::another_object::N` with `CppObjectWrapper` or `Pin`.

**Comment by LeonMatthesKDAB** [comment]
New Proposal:
Rename CppObj -> FFIObj
Rename CppObjWrapper -> CppObj
Use CppObj as the argument for any invokables.
