### ISSUE TITLE
Linkage error on Linux when including *.qrc.cpp

### ISSUE THREAD

**Issue by wolfseifert** [KDAB/cxx-qt#826]
I followed the instructions here:
<pre>
    /// Generate C++ files from [Qt resource .qrc files](https://doc.qt.io/qt-6/resources.html).
    /// <b>The generated file needs to be `#include`d in another .cpp file.</b> For example:
    /// ```no_run
    /// # use cxx_qt_build::CxxQtBuilder;
    /// CxxQtBuilder::new()
    ///     .file("src/cxxqt_module.rs")
    ///     .qrc("src/my_resources.qrc")
    ///     .cc_builder(|cc| {
    ///         <b>cc.file("file_with_include.cpp");</b>
    ///     })
    ///     .build();
    /// ```
    ///
    /// In `file_with_include.cpp`:
    /// ```C++
    /// #include "my_resources.qrc.cpp"
    /// ```
    ///
    /// You also need to [explicitly load](https://doc.qt.io/qt-6/resources.html#explicit-loading-and-unloading-of-embedded-resources)
    /// the resources in your .cpp file by calling `qInitResources()` once before starting your application.
    pub fn qrc(mut self, qrc_file: impl AsRef<Path>) -> Self {
</pre>
and got a linkage error on Linux:
<pre>
error: linking with `cc` failed: exit status: 1
  |
  = note: ld.lld: error: duplicate symbol: qInitResources_resources_qrc()
          >>> defined at resources.qrc.cpp:232 (/home/wolfgang/tmp/cxx-qt-issue/target/debug/build/cxxqt-65f02becf5f1daac/out/resources.qrc.cpp:232)
          >>>            resources.o:(qInitResources_resources_qrc()) in archive /home/wolfgang/tmp/cxx-qt-issue/target/debug/deps/libcxxqt-36f2a5c0ea9d991a.rlib
          >>> defined at resources.qrc.cpp:232 (/home/wolfgang/tmp/cxx-qt-issue/target/debug/build/cxxqt-65f02becf5f1daac/out/resources.qrc.cpp:232)
          >>>            93a1f1269bf6ec12-resources.qrc.o:(.text._Z28qInitResources_resources_qrcv+0x0) in archive /tmp/rustckvUNyy/libqt-static-initializers.a

          ld.lld: error: duplicate symbol: qCleanupResources_resources_qrc()
          >>> defined at resources.qrc.cpp:241 (/home/wolfgang/tmp/cxx-qt-issue/target/debug/build/cxxqt-65f02becf5f1daac/out/resources.qrc.cpp:241)
          >>>            resources.o:(qCleanupResources_resources_qrc()) in archive /home/wolfgang/tmp/cxx-qt-issue/target/debug/deps/libcxxqt-36f2a5c0ea9d991a.rlib
          >>> defined at resources.qrc.cpp:241 (/home/wolfgang/tmp/cxx-qt-issue/target/debug/build/cxxqt-65f02becf5f1daac/out/resources.qrc.cpp:241)
          >>>            93a1f1269bf6ec12-resources.qrc.o:(.text._Z31qCleanupResources_resources_qrcv+0x0) in archive /tmp/rustckvUNyy/libqt-static-initializers.a
          collect2: error: ld returned 1 exit status

error: could not compile `cxxqt-helloworld` (bin "cxxqt-helloworld") due to previous error
</pre>
It turned out that removing <code>cc.file("file_with_include.cpp")</code> (and the file <kbd>"file_with_include.cpp"</kbd> itself) resolved the issue!!!

It seems that the instruction above is not only obsolete, but also harmful (in the case of Linux). It makes no difference on Windows. Please remove it if I am right.

Here is a short reproducer which works as it is, but fails to link on Linux if you activate <code>cc.file("src/resources.cpp")</code> in <kbd>build.rs</kbd>:

[cxx-qt-issue.zip](https://github.com/KDAB/cxx-qt/files/14107940/cxx-qt-issue.zip)

**Comment by ahayzen-kdab** [comment]
Right, i think that `qrc` files are now automatically sorted for you since the move to QML modules etc, so you don't need manually include the cpp file any more. Looks like that has been missed in this part of the docs :-)

The `cc.file("foo.cpp")` is still useful for including custom C++ classes however.

**Comment by Be-ing** [comment]
> Right, i think that qrc files are now automatically sorted for you since the move to QML modules etc, so you don't need manually include the cpp file any more. Looks like that has been missed in this part of the docs :-)

That was implemented as part of implementing QML module support, but it's orthogonal. The `cc.file("src/resources.cpp")` is obsolete now that cxx-qt-build builds the C++ file generated by qrc and links it with `+whole-archive`.
