### ISSUE TITLE
cxx-qt-lib: `QDateTime::setTimezone` overload breaks compilation with Qt 6.7

### ISSUE THREAD

**Issue by LeonMatthesKDAB** [KDAB/cxx-qt#850]
### Discussed in https://github.com/KDAB/cxx-qt/discussions/847

<div type='discussions-op-text'>

<sup>Originally posted by **mystchonky** February 12, 2024</sup>
I copied over the example and when I do cargo run, it errors out (which is not very clear).
the compilation errors happen specifically when building cxx-qt-lib.  [log](https://hastebin.com/share/iseniqepud.rust) 

also it compiles cxx-qt crates twice (maybe not the problem and just related to build.rs)</div>

**Comment by mystchonky** [comment]
@Montel @LeonMatthesKDAB can we get a minor release for `cxx-qt` with this patch in now that Qt 6.7 has been released?

**Comment by ahayzen-kdab** [comment]
I'll take a look at doing a backport for the 0.6 series :-)
