### ISSUE TITLE
Should types in `extern "C++Qt"` need the `#[qobject]` macro

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#878]
When specifying existing types from C++ in an `extern "C++Qt"` block should we require that you specify `#[qobject]` as an attribute to be able to use things like `#[qsignal]` ?

This would make it consistent with the `extern "RustQt"` block and allow for us in the future to support any non-QObject types that need extra syntax than just CXX.

**Comment by LeonMatthesKDAB** [comment]
I would say let's enforce `#[qobject]` for now.

For stabilization that's better as we can always relax the requirement after 1.0, but we can't add a requirement after 1.0.

**Comment by ahayzen-kdab** [comment]
Yes, and this was done in #902
