### ISSUE TITLE
Automatically perform the to/from Rust type conversion inside the CppObjWrapper

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#9]
Once we have #8 the user will always be using the CppObjWrapper. So then in the CppObjWrapper getter/setters etc change the types so that the parameters and return types are the "Rust" types and any conversion is performed inside the CppObjWrapper.

Eg instead of the user needing to change QVariant -> Variant. The CppObjWrapper can do the to_rust() conversion and return Variant.

**Comment by ahayzen-kdab** [comment]
Consider the return type of an invokable as well. The wrapper of the invokable we generate will need to perform the conversion ?

**Comment by ahayzen-kdab** [comment]
Also consider how #58 changes the to_rust() and clone() situations. And see if we can keep a ref for primitive types to avoid a copy ?

**Comment by ahayzen-kdab** [comment]
Once we automatically perform conversions consider if we could rename opaque types, as the user will only need to know about `Url` not `QUrl`.

Can we then have the user use `QUrl` (which is currently `Url`) then have conversion happen with other named types. Or does this cause confusion for cxx when it crosses the bridge?

We might be able to inform cxx of the C++ type in the id field here? if that's not too confusing.
```
unsafe impl ExternType for Url {
    type Id = type_id!("CxxQt::Url");
    type Kind = cxx::kind::Trivial;
}
```

**Comment by ahayzen-kdab** [comment]
Also see if we can remove the `*Impl` from the point of view of users of opaque types. Via getters and setters on the wrapper.

**Comment by LeonMatthesKDAB** [comment]
> Once we automatically perform conversions consider if we could rename opaque types, as the user will only need to know about `Url` not `QUrl`.
> 
> Can we then have the user use `QUrl` (which is currently `Url`) then have conversion happen with other named types. Or does this cause confusion for cxx when it crosses the bridge?
> 
> We might be able to inform cxx of the C++ type in the id field here? if that's not too confusing.
> 
> ```
> unsafe impl ExternType for Url {
>     type Id = type_id!("CxxQt::Url");
>     type Kind = cxx::kind::Trivial;
> }
> ```

Looking at the way #1 is implemented, I think having the naming be `QType` for everything on the user side is the most sensible option. From the users perspective, once we automatically convert everything, they no longer need to touch the internal types, so from their perspective `Color` *is* a `QColor`. That way they also wouldn't have to remember two sets of names for some of the types.

**Comment by ahayzen-kdab** [comment]
* Trivial types are same memory block representation in Rust/C++ so are "same"
* Non moveable types, we have a block of memory, but cannot override rust move behaviour so cannot return
* Allocate on the heap, use C++ methods to access, is that better than below (?)
* Create rust type that is trivial which uses conversion to go to/from Rust/C++

**Comment by LeonMatthesKDAB** [comment]
maybe we should reconsider whether to use a `From<>`, or a custom ToRust Trait for everything that needs a conversion.
Currently, the to_rust method is somewhat unnecessary on most types, as we could just use .into() and implement the conversion directly in the trait impl.
However, it's questionable whether the From implementation is the right semantic here.
