### ISSUE TITLE
Cannot enable QML debugging from build.rs

### ISSUE THREAD

**Issue by classabbyamp** [KDAB/cxx-qt#925]
> based on [this zulip thread](https://cxx-qt.zulipchat.com/#narrow/stream/426347-questions/topic/Enabling.20QML.20debugging.3F/near/433100312)

Qt's builtin [QML debugger can be enabled](https://doc.qt.io/qt-6/qtquick-debugging.html#enabling-the-infrastructure) by defining the symbol `QT_QML_DEBUG` during compilation.

I was trying to enable this to use the [`qmlpreview` tool](https://doc.qt.io/qt-6/qtqml-tooling-qmlpreview.html) while working on the QML of my application, but it does not appear to be working.

This can be minimally reproduced with the [demo from the book](https://kdab.github.io/cxx-qt/book/getting-started/index.html) with the `cc_builder()` line added to `build.rs`:
```rs
use cxx_qt_build::{CxxQtBuilder, QmlModule};

fn main() {
    CxxQtBuilder::new()
        .cc_builder(|cc| { cc.define("QT_QML_DEBUG", None); })
        .qt_module("Network")
        .qml_module(QmlModule {
            uri: "com.kdab.cxx_qt.demo",
            rust_files: &["src/cxxqt_object.rs"],
            qml_files: &["qml/main.qml"],
            ..Default::default()
        })
        .build();
}
```
then:
```sh
$ cargo clean
$ cargo build
$ qmlpreview target/debug/demo
QML Debugger: Ignoring "-qmljsdebugger=file:/tmp/qmlpreview.UWBQqC,block,services:QmlPreview". Debugging has not been enabled.
```
the message shown indicates the debugger was not enabled when compiling.

**Comment by ahayzen-kdab** [comment]
OK i've managed to make `QML debugging is enabled. Only use this in a safe environment.` appear.

Appears you also somewhere need to include `<QQmlDebuggingEnabler>` or `<QtQuick>` for the object to be created in Qt.

So you can either ensure that you have 

```rust
unsafe extern "C++" {
   include!(<QQmlDebuggingEnabler>);
}
```

or 

```rust
unsafe extern "C++" {
   include!(<QtQuick>);
}
```

in one of your bridges (note that with QtQuick you also need to specify `.qt_module("Quick")` in the build.rs.

Or if you have C++ code already included you can likely add one of these to your headers.

**Comment by classabbyamp** [comment]
> Appears you also somewhere need to include `<QQmlDebuggingEnabler>` or `<QtQuick>` for the object to be created in Qt.
> 
> So you can either ensure that you have
> 
> ```rust
> unsafe extern "C++" {
>    include!(<QQmlDebuggingEnabler>);
> }
> ```

thanks, that worked to enable the debugger.

I now get
```
QML debugging is enabled. Only use this in a safe environment.
QML Debugger: Connecting to socket /tmp/qmlpreview.GCqwrM...
qt.core.plugin.loader: /usr/lib/qt6/qml/QtQml/WorkerScript/libworkerscriptplugin.so: failed to map to memory: Unknown error
qt.core.plugin.loader: /usr/lib/qt6/qml/QtQml/WorkerScript/libworkerscriptplugin.so: failed to map to memory: Unknown error
qt.core.plugin.loader: /usr/lib/qt6/qml/QtQml/WorkerScript/libworkerscriptplugin.so: failed to map to memory: Unknown error
qt.core.plugin.loader: /usr/lib/qt6/qml/QtQml/WorkerScript/libworkerscriptplugin.so: failed to map to memory: Unknown error
QQmlApplicationEngine failed to load component
qrc:/qt/qml/com/kdab/cxx_qt/demo/qml/main.qml:1:1: module "QtQuick" version 2.12 cannot be imported because:
module "QtQml" version 2.12 cannot be imported because:
The file '/usr/lib/qt6/qml/QtQml/WorkerScript/libworkerscriptplugin.so' is not a valid Qt plugin.
```
when using `qmlpreview` but I'm not sure that's related to cxx-qt...

**Comment by ahayzen-kdab** [comment]
Those errors look related to Qt, and note with Qt 6 QML you don't need the version so you likely just want `import QtQuick` rather than `import QtQuick 2.12` which may change the warning.

**Comment by classabbyamp** [comment]
I've confirmed this isn't related to cxx-qt or rust + qt, so the original issue is solved, closing.
