### ISSUE TITLE
Use the `naming` module everywhere

### ISSUE THREAD

**Issue by LeonMatthesKDAB** [KDAB/cxx-qt#939]
This module is more complete than our previous `CombinedIdent` approach.

Make sure to use it everywhere, especially in generation.

**Comment by BenFordTytherington** [comment]
CombinedIdent has now been completely removed from the codebase as of PR https://github.com/KDAB/cxx-qt/pull/1005

**Comment by LeonMatthesKDAB** [comment]
> CombinedIdent has now been completely removed from the codebase as of PR #1005

Awesome!
I'll still go through the codebase and check whether there's places where we need to replace some more `Ident` instances with `Name`, but after that we can close this issue :partying_face:

**Comment by LeonMatthesKDAB** [comment]
I think this is done now.
@BenFordTytherington can you confirm and close the issue? 🤔
