### ISSUE TITLE
Which version of qt was supported?

### ISSUE THREAD

**Issue by DannyBaobei** [KDAB/cxx-qt#976]
I'm trying build this project with qt 5.6.3 but failed

**Comment by LeonMatthesKDAB** [comment]
Hello @DannyBaobei , thank you for your interest in CXX-Qt.

We officially support & test Qt 5.15 and Qt 6. So a failure with Qt 5.6.3 isn't unexpected.
If you can, please update your Qt version, ideally to Qt 6.
