### ISSUE TITLE
Make sure CXX_QT_ vs. CXXQT_ prefix is used consistently

### ISSUE THREAD

**Issue by LeonMatthesKDAB** [KDAB/cxx-qt#996]
We currently use both CXX_QT_ and CXXQT_ for some variable prefixes.

As established in https://github.com/KDAB/cxx-qt/pull/983#discussion_r1674222739 , we should unify this to a single prefix that should be used everywhere.
Likely CXX_QT_ is the prefix to go with.

So rename all variables that start with CXXQT_ to start with CXX_QT_ instead.

**Comment by ahayzen-kdab** [comment]
Note that we use `cxxqt_import_crate` in CMake, should that be changed too ?

**Comment by LeonMatthesKDAB** [comment]
Yup, doing that as part of #999
